### ISSUE TITLE
Misconfiguration errors to help adoption

### ISSUE THREAD

**Issue by MrWako** [corazawaf/coraza#1007]
## Summary

I've recently realized that we don't have Coraza correctly configured to buffer request responses, but its taken quite a bit of fiddly debugging since the issue was only happening infrequently. I think it could help adoption of the package if the WAF errored a bit more obviously in this situation.

### Basic example

I've been deploying Coraza in a reverse proxy deployed in Kubernetes. Our containers use a bare minimum scratch-based image with no access to the container file-system. I now realize this is going to be an issue for larger requests which are buffered (I'll probably mount an ephemeral volume ...). However, as a newbie to the package this took quite a long time to diagnose as it only happened on a few requests and only in the wild, so needed to find a reproducer etc etc.

Anyway my suggestion is:
* When creating a new WAF, check that the tmp directory is accessible and writeable if its expected to be used for buffering (I realize there's also the `no_fs_access` build tag too). If not error.
* If the WAF fails to the point that the request doesn't even get processed I think there should be a non-debug error log message. Currently there is only a debug log message: `failed to append request body: open /tmp/body2522281953: no such file or directory`, but the debug logs are very chatty and its completely infeasible to have these enabled for anything other than short periods in a debug environment. Apart from the debug log there's no indication that the WAF has failed and the request has not been processed.
* If the WAF fails to the point that the request doesn't even get processed then I think it should probably also return a 500.

Here's a test illustrating the issue with some comments. In this example we get a 200 status code back, in our really proxy we are seeing 0 status codes.

```
import (
	"bytes"
	"fmt"
	"net/http"
	"net/http/httptest"
	"os"
	"strconv"
	"strings"
	"testing"

	coreruleset "github.com/corazawaf/coraza-coreruleset"
	"github.com/corazawaf/coraza/v3"
	coraza_http "github.com/corazawaf/coraza/v3/http"
	"github.com/corazawaf/coraza/v3/types"

	"github.com/stretchr/testify/assert"
)

func Test_WAF_Buffer_Error(t *testing.T) {
	r := testBigPostRequest()
	rw := httptest.NewRecorder()

	waf := testWAF(t)
	h := coraza_http.WrapHandler(waf, http.HandlerFunc(func(rw http.ResponseWriter, r *http.Request) {
		// we never actually end up calling the handler
		rw.WriteHeader(http.StatusCreated)
		rw.Write([]byte("created"))
	}))

	// when we process the request we only get a Debug log. Since the debug logs are very chatty
	// we only temporarily activate them whilst debugging. For an issue like this that is causing the
	// request to fail I thin I would expect an error logged via the errorCallBack. Otherwise its
	// pretty hard to spot in the wild, especially if the failure returns a non-suspicious 200 code.
	h.ServeHTTP(rw, r)
	assert.Equal(t, http.StatusInternalServerError, rw.Code)
}

func testWAF(t *testing.T) coraza.WAF {
	errorCallBack := func(err types.MatchedRule) {
		msg := err.Message()
		id := err.Rule().ID()
		file := err.Rule().File()
		serverity := err.Rule().Severity().String()
		uri := err.URI()
		data := err.Data()
		fmt.Printf("WAF [%s] %s [%s] ID: %d [%s] URI: %s\n", serverity, msg, data, id, file, uri)
	}

	// set the tmp dir to a non-existent location so that we can't buffer the request
	os.Setenv("TMPDIR", "/non-existent-dir")

	config := coraza.NewWAFConfig().
		WithErrorCallback(errorCallBack).
		WithRootFS(coreruleset.FS).
		WithDirectives("Include @coraza.conf-recommended").
		WithDirectives("Include @crs-setup.conf.example").
		WithDirectives("SecRequestBodyInMemoryLimit 128").
		WithDirectives("SecResponseBodyAccess Off").
		WithDirectives("SecRuleEngine On").
		WithDirectives("Include @owasp_crs/*.conf")

	// I think ideally NewWAF would error if the tmp dir isn't actually writeable to. This would
	// help identify mis-configuration of the WAF at startup time
	waf, err := coraza.NewWAF(config)
	assert.NoError(t, err)
	return waf
}

func testBigPostRequest() *http.Request {
	target := `/foo`
	body := []byte(`{"names":["` + strings.Repeat("a very long name", 10) + `"]}`)
	r := httptest.NewRequest(http.MethodPost, target, bytes.NewBuffer(body))
	r.Header.Add("Content-Type", "application/json")
	r.Header.Add("Content-Length", strconv.Itoa(len(body)))
	return r
}
```

### Motivation

Avoid others hitting the same problem and potential abandoning Coraza. Make Coraza behaviour less mysterious and easier to debug/correct.

**Comment by jcchavezs** [comment]
This is amazing feedback. We truly need to address this issue with the
filesystem. Are you up for a PR?

Also as for chatty logs, it is not the first time people brings this to my
attention and I wonder if we should do a review. I personally did a review
myself and tried to improve the situation but maybe I focused on matched
rules debugging.

Anyways, thanks for this.

**Comment by MrWako** [comment]
@jcchavezs - yes I'm up for trying to get a PR together. I'll see how I get on!

**Comment by jcchavezs** [comment]
Friendly ping @MrWako

**Comment by jcchavezs** [comment]
@M4tteoP since you got some momentum could you please take care of this?

**Comment by M4tteoP** [comment]
Hey, thanks for the feedback. The check at startup time is being implemented in https://github.com/corazawaf/coraza/pull/1030.

I wish to double-check the verbosity of debug logs. They come with different levels of verbosity configurable via [SecDebugLogLevel](https://coraza.io/docs/seclang/directives/#secdebugloglevel). I took a quick look at the code where we generate debug logs at the error level (the least verbose level before not printing debug logs at all), and they all seem to be quite severe and worth being printed at this level. So, strictly speaking about debug logs, are you experiencing noise even by setting `SecDebugLogLevel` to `1`?

The naming is actually a bit misleading, but the errorCallBack is expecting to receive a `types.MatchedRule`, so is going to print errors triggered by rules rather than related to the engine (For that the debug logger at Error level is used).
