### ISSUE TITLE
Add two new security verification functions to achieve flexible use of security verification

### ISSUE THREAD

**Issue by k4n5ha0** [corazawaf/coraza#1044]
## Summary

Two new functions are expected, isSqli and isXss，functions with no log but more speed

### Basic example
```
	cfg := coraza.NewWAFConfig().
		WithRootFS(coreruleset.FS).
		WithDirectives("Include @coraza.conf-recommended").
		WithDirectivesFromFile("@owasp_crs/REQUEST*.conf")
	waf, err := coraza.NewWAF(cfg)
	if err != nil {
		t.Error(err)
	}
	sqliattack := waf.isSqli("some input string")
	xssattack := waf.isXss("some input string")
	if sqliattack != nil {
		// is sqli attack
	}
	if xssattack != nil {
		// is xss attack
	}
```

### Motivation

I want to integrate the security verification capability into the development framework

**Comment by fzipi** [comment]
You can already do that using rules. See the `@detectSQLi` and `@detectXSS` operators.

**Comment by k4n5ha0** [comment]
> You can already do that using rules. See the `@detectSQLi` and `@detectXSS` operators.

（"some input string"） is just  the value entered by the user，not all http content

**Comment by fzipi** [comment]
If you want a library for doing that, check libinjection.

**Comment by k4n5ha0** [comment]
> If you want a library for doing that, check libinjection.

use
https://github.com/corazawaf/libinjection-go
and  regex in coreruleset will be fine.
thx
