### ISSUE TITLE
coraza-crs-docker

### ISSUE THREAD

**Issue by loukaniko85** [corazawaf/coraza#1095]
OWASP provide an official ModSecurity CRS container - https://github.com/coreruleset/modsecurity-crs-docker . It would be fantastic to have a coraza-crs-docker take its place.

I'm using this in the interim period - https://github.com/loukaniko85/waf with this traefiik plugin https://plugins.traefik.io/plugins/644d9a72ebafd55c9c740848/mx-m-owasp-crs-modsecurity-plugin .

**Comment by fzipi** [comment]
Like [this one](https://github.com/coreruleset/coraza-crs-docker/)?

**Comment by fzipi** [comment]
For now it is implemented using Caddy. But the idea is to have additional versions with just the bare middleware, traefik, etc (if needed).

But then that will be provided by the CRS team, not the Coraza team.

**Comment by loukaniko85** [comment]
How did I miss this!? I made my own fork instead.. Thank you!

**Comment by fzipi** [comment]
No worries. You can start contributing there also! 💪

**Comment by M4tteoP** [comment]
hey @loukaniko85, can we close this?

**Comment by loukaniko85** [comment]
🤝

**Comment by M4tteoP** [comment]
🚀
