### ISSUE TITLE
Regression tests for full feature matrix

### ISSUE THREAD

**Issue by jptosso** [corazawaf/coraza#1182]
Right now, we are just testing regression for memoize. We should programmatically build tests for each feature flag set permutation or build tag.
Quoting our build tags from README:
>coraza.disabled_operators.* - excludes the specified operator from compilation. Particularly useful if overriding the operator with plugins.RegisterOperator to reduce binary size / startup overhead.
coraza.rule.multiphase_valuation - enables evaluation of rule variables in the phases that they are ready, not only the phase the rule is defined for.
memoize_builders - enables memoization of builders for regex and aho-corasick dictionaries to reduce memory consumption in deployments that launch several coraza instances. For more context check https://github.com/corazawaf/coraza-caddy/issues/76
no_fs_access - indicates that the target environment has no access to FS in order to not leverage OS' filesystem related functionality e.g. file body buffers.
coraza.rule.case_sensitive_args_keys - enables case-sensitive matching for ARGS keys, aligning Coraza behavior with RFC 3986 specification. It will be enabled by default in the next major version.

We should consider tests for each permutation of build tags.

**Comment by M4tteoP** [comment]
Completed via https://github.com/corazawaf/coraza/pull/1214
