### ISSUE TITLE
Loading file in coraza.conf fails on Go 1.23

### ISSUE THREAD

**Issue by ErazerBrecht** [corazawaf/coraza#1208]
## Description

Describe the issue that you're seeing.
We are using the Coraza Caddy plugin. This week our builds don't run anymore.
When launching Caddy it crashes.

After some debugging we found that the builder image from Caddy instals the newer Go version since last week.

I was first planning to create the issue on the Caddy plugin repo.
But after some researcher the error is thrown from Coraza itself

Being specifically this line:
https://github.com/corazawaf/coraza/blob/a45e359e998e1dab94288b1f62cea9fd452ea15a/internal/seclang/parser.go#L64

### Steps to reproduce

https://github.com/ErazerBrecht/coraza.git

The first commit works, the second commit it breaks.

### Expected result
It shouldn't crash when specifying a specific coraza config. 

### Actual result
> invalid WAF config from string: failed to readfile: read /opt/coraza/config/coraza.conf: invalid argument

**Comment by M4tteoP** [comment]
Hey @ErazerBrecht, thanks for reporting this!
I managed to reproduce it and create a minimal repro that does not include caddy: https://github.com/corazawaf/coraza/compare/main...minimal_repo_readfile.
I need some more time or help to come up with a fix, but here is what I think is happening:
The parser calls `fs.ReadFile` which internally performs a type assertion `fsys.(ReadFileFS)`.
For some reason, starting from Go 1.23, this assertion is failing, and therefore `ValidPath` function is called.
See https://cs.opensource.google/go/go/+/refs/tags/go1.23.3:src/io/fs/readfile.go;l=32.
`ValidPath` function is now allowing to have a path starting with `/`, just like `/opt/coraza/config/coraza.conf`.
So, looks like the root fs we are providing with `WithRootFS(mergefs.Merge(coreruleset.FS, io.OSFS))` does not implement anymore the `ReadFileFS` interface.

I'll keep investigating from here, but I wanted to update you on the issue.
As a workaround, you might try to use a relative path (if doable).

**Comment by M4tteoP** [comment]
Actually, I think found it.
Via https://go-review.googlesource.com/c/go/+/560137/4/src/io/fs/sub.go#b36 the error message has been changed from `invalid name` to `invalid argument`, therefore we are not catching it anymore and we are not using the correct root to access the file. See https://github.com/jcchavezs/mergefs/blob/07f27d25676181074133e7573825402b88bf2f99/readfile.go#L23-L27

**Comment by M4tteoP** [comment]
Hi @ErazerBrecht, the fix has been pushed to the main branch of [coraza-caddy](https://github.com/corazawaf/coraza-caddy). If you could give it a try and let me know if it works, I'd really appreciate it!

**Comment by ErazerBrecht** [comment]
@M4tteoP
Thank you very much! It's the first thing I'll do tomorrow!
Enjoy the rest of your day!

Sincerely, Brecht

**Comment by ErazerBrecht** [comment]
@M4tteoP 
I confirm this is fixed 🚀
