### ISSUE TITLE
[owasp-modsecurity compatibility] base64Encode method

### ISSUE THREAD

**Issue by tty2** [corazawaf/coraza#1252]
## Summary

coraza doesn't implement method base64Encode
owasp-modsecurity [has this method](https://github.com/owasp-modsecurity/ModSecurity/wiki/Reference-Manual-(v3.x)#user-content-base64Encode)

### Basic example

https://github.com/owasp-modsecurity/ModSecurity/wiki/Reference-Manual-(v3.x)#user-content-base64Encode

### Motivation

OWASP modsecurity compatibility

**Comment by fzipi** [comment]
Thanks for reporting! Are you up for a PR?

**Comment by tty2** [comment]
Hi
I'm gonna take it to implement soon

**Comment by tty2** [comment]
Implemented with #1257
