### ISSUE TITLE
Last discussions before v2 release

### ISSUE THREAD

**Issue by jptosso** [corazawaf/coraza#150]
### 1. ```func NewBodyBuffer(tmpDir string, memLimit int64) *BodyBuffer``` should receive a ```coraza.BodyBufferOptions``` instead?

- [x] #153

### 2. ```Makro.Tokens()``` should return a list of tokens? Not the count

@fzipi : How is this being used? Of course, with the list you can always len.

@jptosso : I don't see any use case for the tokens, I created this function for rx, if there are expandable tokens, RX will recompile the regex on each rule evaluation. What about replacing .Tokens with .IsExpandable()?

### 3. ```MatchData``` should be moved to types

@fzipi : Definitely yes. Even maybe to a new rules.go?

@jptosso : ok, moving to types/rules.go

- [x] #152

### 4. ```MatchedRule``` should be redesigned

@fzipi : Well, this can be applied to anything ;). How is the question? What are we trying to solve?

@jptosso : it works just like in modsecurity but it is not flexible at all

### 5. ```tx.ParseRequestReader`` should be renamed to ```tx.ProcessRequestReader````

@fzipi: Why not just RequestReader? Also, we should focus on what's inside. I don't like the Don't use in production yet! ;)

@jptosso: It is already production ready, I will change the notice. It's just a helper to wrap all phases for http.Requests

### 6. ```Interruption``` should be renamed to ```Intervention``` like in modsecurity? 

@fzipi: Hmmm 🤔 Let's take some time to think about the best name for it...

@jptosso: Not that important, but for consistency, an interruption necessarily interrupts, as a concept, but an intervention may do something different?

### 7. ```RemoveRuleTargetById``` should receive a range instead of an int value?

Has to fix

- [x] #163

### 8. For stream inspection we should receive a new type of object on the operators instead of a string but it will only benefit PM and RX, should we leave this for v3?

v3 issue

### 9. Should we unexport some AuditLog fields?

I think this one is discarded, we need to write the audit logs somehow.

### 10. ```seclang.ParseRule``` should be unexported?

@fzipi: Maybe. What is the use case now? Also, there are some types we might want to move in rule_parser.go?

@jptosso: It is consumed by SecRule and SecAction, I think it should be unexported unless we want new directive plugins to build rules (?)

### 11. Maybe transform RuleOptions into DirectivesOptions so we stop using waf.Config to share variables across directives

@fzipi: This makes total sense. And it is easy for mocking up in tests.

@jptosso: Will be implemented.

- [x] #171

### 13. More tests for phase 4

- [x] #156

Any other suggestion is welcome :3

**Comment by fzipi** [comment]
> 1. `func NewBodyBuffer(tmpDir string, memLimit int64) *BodyBuffer` should receive a `coraza.BodyBufferOptions` instead?

Definitely yes.

> 
>     2. `Makro.Tokens()` should return a list of tokens? Not the count

How is this being used? Of course, with the list you can always `len`.

> 
>     3. `MatchData` should be moved to types

Definitely yes. Even maybe to a new `rules.go`?

> 
>     4. `MatchedRule` should be redesigned

Well, this can be applied to anything ;). _How_ is the question? What are we trying to solve?

> 
>     5. `` tx.ParseRequestReader`` should be renamed to  ``tx.ProcessRequestReader````

Why not just `RequestReader`? Also, we should focus on what's inside. I don't like the `Don't use in production yet!` ;)

> 
>     6. `Interruption` should be renamed to `Intervention` like in modsecurity?

Hmmm 🤔 Let's take some time to think about the best name for it...

> 
>     7. `RemoveRuleTargetById` should receive a range instead of an int value?

Isn't [already doing that?](https://github.com/jptosso/coraza-waf/blob/3631394d2249b89b792ae76ab4552a00459b31b6/actions/ctl.go#L76). What it should do maybe, is receive a regex on ARGS. That would be ❤️ , and a much needed shortcut.

> 
>     8. For stream inspection we should receive a new type of object on the operators instead of a string but it will only benefit PM and RX, should we leave this for v3?

v3 I think.

> 
>     9. Should we unexport some AuditLog fields?

Sure. Which ones?

> 
>     10. `seclang.ParseRule` should be unexported?

Maybe. What is the use case now? Also, there are some types we might want to move in `rule_parser.go`?

> 
>     11. Maybe transform RuleOptions into DirectivesOptions so we stop using waf.Config to share variables across directives

This makes total sense. And it is easy for mocking up in tests.

> 
>     12. Review [Implement rule reload mechanism #151](https://github.com/jptosso/coraza-waf/issues/151)

:+1:

> 
>     13. More tests for phase 4
> 
> 
> Any other suggestion is welcome :3

**Comment by jptosso** [comment]
V2 was released
