### ISSUE TITLE
Implement rule reload mechanism

### ISSUE THREAD

**Issue by jptosso** [corazawaf/coraza#151]
Maybe we could replace waf.Rules pointer in runtime without affecting the users but I'm not sure if it might panic in some cases

Other mechanism would be to remove waf.Rules and replace it with:

```go
func (w *Waf) Rules() *RuleGroup {
  w.rgMux.RLock()
  defer w.rgMux.RUnlock()
  return w.rules
}
````

That way we could lock ```.Rules()``` whenever we are refreshing the rules with something like ```wwaf.SetRules(someRuleGroup)```.

**Comment by bxlxx** [comment]
This is still happening.

**Comment by jptosso** [comment]
Maybe this problem should be solved by the connectors and not by Coraza ?
