### ISSUE TITLE
Implement new directive for rate limiting

### ISSUE THREAD

**Issue by fzipi** [corazawaf/coraza#165]
## Summary

Rate limiting is a feature that needs to be concocted using a combination of _SecRules_ that adds complexity and it is mandatory for the today Web. While you have the scaffolding to create it, is should be easy to create and maintain.

### Basic example

The proposal is to add a new directive, maybe `SecRuleRateLimit`, where you define:
- the url to protect
- the rate limit per second/minute/etc.
- the action when the limit is reached:
   - return http code 429
   - send it to a tarpit
- also, when to clear the rate limit

### Advanced example

The advanced setting should be able to synchronize this limit using a persistent storage or other communication method. Depending on the load, it will be very common to run a cluster of Coraza protected servers. Hence the need for syncing between all deployed servers.

There are many examples on how to do this using, for example, in memory or Redis. We should discuss if this requires additional go modules, which one is the best for this case.

### Motivation

Having a unique directive that clearly states what will be the result is mandatory.

**Comment by ShiMing-Q** [comment]
Got this simple one, https://github.com/uber-go/ratelimit

**Comment by jptosso** [comment]
@ShiMing-Q it looks promising, do you think @fzipi this should work across nodes in a distributed environment? Or is it's ok to handle it per node?

**Comment by fzipi** [comment]
I was thinking more on https://github.com/mennanov/limiters maybe.

**Comment by fzipi** [comment]
Another place to have a look is https://github.com/owlwang/caddy-ratelimit.

**Comment by fzipi** [comment]
No "visible" activity. But I am on top of it.

**Comment by ShivanshVerma-coder** [comment]
Hey @fzipi I was thinking of implementing this for v4. 

I studied few algorithms for implementing Rate Limiting, I had to ask are we thinking of implementing it from scratch or depend upon a third party library for it? Also I did see a few libraries mentioned in the comments of the issue.

1) [https://github.com/owlwang/caddy-ratelimit](Caddy) - As far as I saw It requires a new HTTP server to be run and we will have to send requests to know if we can allow requests, which will be very costly as traffic will be very high for this HTTP server, a gRPC would have been better choice. (Please correct me if I misunderstood the library).

2) https://github.com/uber-go/ratelimit - It seems fine if we are thinking of directly implementing Leaky Bucket in our app, but will handle it per node. If we want to implement leaky bucket then we can create a complete different service and use this library in it, interact with our main application through gRPC.

3) https://github.com/mennanov/limiters - This one seems more promising as it has variety of options for choosing algorithm, gives support for redis and etcd out of the box, has shown a gRPC implementation too. Seems workable.


I think creating a decoupled gRPC service for Rate Limiting which uses ( https://github.com/mennanov/limiters ) as 3rd party and interacting with it from main service should be a good choice.

There are so many options, What do you think?

**Comment by fzipi** [comment]
Hi @VermaShivansh, thanks for joining.

My vision is:
- Coraza is a library, and it should remain independent of things like the actual algorithm it is being used for rate limiting (or even if we are using rate limiting at all). 
- Coraza should provide options for people to choose from and have a clear interface so people can implement their own rate limit, provided there is an interface.
- No additional services, gRPC, etc. This must be embedded for speed.
- What happens if we want to do distributed rate limited? This is an advanced feature and needs just to be solved by the persistence layer. 👉 Let's forget about this one, for now. There is an ongoing idea of having variables with persistence, so when ready we switch to using those.

So the questions that I had before when thinking about implementing this were:
  - core or plugin? This one is easy, clearly must be a plugin. 
  - do we embed this in the _secrule_ language using a new operator, actions, or what? This is not easy, but a simple answer for this was to use new directive(s), consolidating all the options there. So then the implementation should add new directives like 
    - `SecRateLimitOptions <algorithm, configuration in general>`
    - The way for enforcing rate limit might have two options:
      -  using `SecRateLimit OPERATOR VAR ACTIONS`. It should behave exactly like the regular `SecRule` syntax.
      - (preferred) using a new action `ratelimit`, in a regular `SecRule`. Probably this is the less intrusive and we keep the directives small. Also allows us to define different `status` (e.g. 429, or people might want to just use 403`).
    - Both should apply the rate limit based on the previously defined options. We might have in the future different options per context? (but then this might be solved by just creating a `NewWAF`.

Implementation should:
- Start by adding the scaffolding for a plugin
- Add the new directives for configuration, e.g. `SecRateLimitOptions` and enforcement `SecRateLimit`.
- Tests for all of the above.
- Then, after this is all done, implement the actual rate limit.
- Rate limit **must be an interface**. 
- Methods could be something like:
  - creating a `NewRateLimiter` with the options from the `SecRateLimitOptions`
  - `SecRateLimit` directive, or `ratelimit` action will call the corresponding method
  - the core method could be something like `HasToRateLimit`, but we can get a better name for it... :)
- Rate limit must `count` when the operator in the vars matches, including all chains. If count exceeds the limit, then it should deny/block. Another option to this would be that `ratelimit` acts as a non-disruptive action, and there is a disruptive action also in the rule. E.g. `SecRule ... "ratelimit,redirect,..."` or `SecRule ... "ratelimit,deny,status:429"`.
- Tests for all the above. Then, more tests.
- Document everything clearly.

You can get ideas from the rate limiter implementations above. I think Caddy has a reasonable interface but use your imagination there. If you have any doubts, just shout!

CC @jptosso @anuraaga @jcchavezs wdyt? reasonable enough?

**Comment by VermaShivansh** [comment]
Hey @fzipi , just wanted to make sure, I am taking help from [these](https://coraza.io/docs) docs as some of the things are new for me like SecLang, Directives and creating plugin. I will also go through code of the existing plugins once. Is there anything else also I should do which can help me out?

**Comment by fzipi** [comment]
I think that is pretty much everything there is out there... In any case, you can ask for advice at the #coraza channel in the OWASP Slack.

**Comment by VermaShivansh** [comment]
Hey @fzipi , I am taking the idea of code pattern for plugin from [geoip](https://github.com/corazawaf/coraza-geoip) plugin. I am creating my own personal repo for the time being for the plugin.

**Comment by fzipi** [comment]
@VermaShivansh Any news on this?

**Comment by VermaShivansh** [comment]
Hi @fzipi, I converted it into a GSOC 2023 project by talking to @jcchavezs .

**Comment by jptosso** [comment]
Already implemented https://github.com/VermaShivansh/coraza-ratelimit-plugin
