### ISSUE TITLE
Monthly meeting agenda (March 2022)

### ISSUE THREAD

**Issue by jptosso** [corazawaf/coraza#180]
- **Date:** _Wednesday, March 30 at 12 p.m. UTC_
- **Previous agenda:** https://github.com/corazawaf/coraza/issues/162

### Current agenda
1. Project status
2. Pending Feb topics
    1. Gift on PRs: @jptosso  will bring proposals with price and "rules"
    2. Project core values: @jptosso  will bring the proposal of core values
    3. Where to publicly store all coraza research? Public confluence, website, or GH wiki
    4. Side projects status and future (website, sandbox, docker, caddy, traefik, gin, and coraza-server)
    5. README structure
9. ~#186~ (moved to v3)
16. #207 
10. #187 
11. #208 
12. #190 
13. #192 
14. #196
15. #150 

### How to join?
1. Join OWASP slack: https://owasp.org/slack/invite
2. Join #coraza channel: https://owasp.slack.com/archives/C02BXH135AT

**Comment by bxlxx** [comment]
## Meeting Notes
### Project Status
1. The project is now part of OWASP lab project, labeled as OWASP Coraza
2. New upcoming sponsor(TBD)
3. We have completed all milestones for [v2 release](https://github.com/corazawaf/coraza/releases/tag/v2.0.0)
4. We have people interested in GSOC, feel free to join [#coraza-gsoc](https://owasp.slack.com/archives/C03217HAQQ6)
5. We have made a lot of progress in libcoraza(C wrapper)

### Nginx/Apache Connector
At present, there is not much work in Apache Connector, but libcoraza is already working, but it still leaks some memory. The Nginx Connector is basically a fork of the libmodsecurity connector. It is compiling, the autotooling is ready and we are missing some progress regarding the transaction intervention and logging. This is a core project in our roadmap until we find a maintainer.

## Bug Bounties
