### ISSUE TITLE
SecMarker/SecAction occurrence polluting MatchedRules with nil matches

### ISSUE THREAD

**Issue by piyushroshan** [corazawaf/coraza#182]
## Description

Do away of nil MatchedRules for SecMarker
SecMarker currently adds a Rule Match for every occurrence. We should do away with that. There is no point in storing nil matches. 
Ignoring implementation details  SecMarker or SecAction rule matches only cause confusion from an external perspective.

SecMarker or SecAction occurrence can be logged for debug purposes but it should not be stored and added to MatchedRules.

### Steps to reproduce

Add SecMarker to rules and check MatchedRules post processing transaction.

### Expected result
SecMarker or SecAction should not add to MatchedRules

### Actual result
SecMarker or SecAction adds a MatchedRule for every occurrence in rule set.

**Comment by ShiMing-Q** [comment]
The r.Log will be set to false in `directiveSecMarker` for SecMarkers.
The matched rule will be added only if r.log == true.
So I don't think the SecMarker will be added into MatchedRules. @jptosso 

![image](https://user-images.githubusercontent.com/10385477/155957832-25452a61-3fb3-4f60-8cea-7f0f5b2eec45.png)
![image](https://user-images.githubusercontent.com/10385477/155957853-7a79e8a0-f383-4610-abbf-5c6827cff8a9.png)

**Comment by jptosso** [comment]
You are right, this should be merged with https://github.com/corazawaf/coraza/issues/172, we are removing the IF r.Log and creating additional conditions for logging. Closing in favor of #172
