### ISSUE TITLE
Optimize variable and prepare for persistence

### ISSUE THREAD

**Issue by jptosso** [corazawaf/coraza#186]
Variables are currently handled as an array of collections, each index represents a constant provided by the types/variables package. 

Each time you query a variable you must walk the array and find the constant index, like ```variables.RequestAddr```.

To get a collection you use ```tx.GetCollection(variables.RequestAddr)```

I think it is time to move to a faster approach, like instead of an array we use static variables, like ```tx.Variables.RequestAddr```.

One big challenge is how do we tell the rule which variable to use, do we create a huge switch? 

Other important change we require is to transform coraza.Collection into an interface that allows multiple variables types, just like modsecurity does:

- Single Value: The variable only has one value
- Key-Value: The variable is a map map[string]string (like GEO)
- Key-Slice: The variable is a map map[string][]string (like request_headers)
- Key-Slice Proxy: The variable is a Key-Slice that connects multiple Key-Slice variables (like ARGS that connects ARGS_GET and ARGS_POST)
- Persistent: The variable is a Key-Slice persistent variable (like IP)

This change must be transparent and shouldn't affect high-level features.

Questions:

- Should we implement this?
- Should we push it to v2? Or we wait for v3?

**Comment by emerzon** [comment]
One nice improvement / missing feature from ModSecurity would be the ability to replicate Collections to different instances, maybe using something like Redis for persistence. So please have this in mind :)

**Comment by jptosso** [comment]
Hey @emerzon , thank you for your suggestion. This is part as the plan that I should have specified. Persistent collections must be an interface and must be extendable with plugins. You should be able to migrate from Redis to Memcached, in memory databases or whatever you want. @fzipi once proposed to use https://github.com/dgraph-io/badger as the default engine.

I see Coraza deployed in clusters, so keeping persistent variables across instances seems like a priority.

**Comment by jptosso** [comment]
@fzipi @bxlxx, do you think we should have these interfaces created for the v2 release? or is this a v3 issue?

**Comment by bxlxx** [comment]
I don't think we need to have these interfaces in the v2 release. It should appear in V3 as a new feature. The things we should do in the v2 version should be bug fixes, plugin repository establishment, document improvement, and performance test results display. like @fzipi said: We should write more (docs) to write less (code).

**Comment by fzipi** [comment]
Sorry for the delay. This is a v3 issue. But a good start on the discussion!
