### ISSUE TITLE
Response Body Processor

### ISSUE THREAD

**Issue by jptosso** [corazawaf/coraza#187]
Seclang currently only supports body processing for request bodies. It's usually hard to handle response bodies because HTML payloads are huge but what about APIs? I think it's time to take Coraza to the next level and recycle request body processors to be used in the response body. It should work like this:

```
SecRule RESPONSE_HEADERS:content-type "application/json..." "id:1000,phase:3,ctl:responseBodyProcessor=JSON"
SecRule RESPONSE_ARGS:user_id "@gt 1000" "id:1000,phase:4,msg:'Response user ID > 1000'"
```

To achieve this we must rewrite the body processor engine because it currently hardcodes the variable it will affect, like ARGS_GET.

We could also extend the body processors and add HTML support for JQUERY syntax: https://github.com/PuerkitoBio/goquery (just an idea)

- We could implement this into de bodyprocessors package and rename ```VariableHook()``` into ```HookRequest()``` and ```HookResponse()```. 
- Hooks for responses should be optional, as response won't support multipart nor URL encoded
- The logic for the response body processor must be the same as the request body processor, with the exception that there will be no default body processor

**Comment by jcchavezs** [comment]
Ping @M4tteoP
