### ISSUE TITLE
Rule should hold the Log action specified and not default to false

### ISSUE THREAD

**Issue by piyushroshan** [corazawaf/coraza#191]
## Description

Rule should hold the Log action specified and not default to false.

### Steps to reproduce

Create a simple rule.
```
SecRule REQUEST_HEADERS "attack" "id:20,phase:1,msg:'test rule1',logdata:'something'"
SecRule REQUEST_HEADERS "attack" "id:21,nolog,phase:1,msg:'test rule1',logdata:'something'"
SecRule REQUEST_HEADERS "attack" "id:22,log,phase:1,msg:'test rule1',logdata:'something'"
```

### Expected result

rule.Log is set to Default for 20
rule.Log is set to NoLog for 21
rule.Log is set to Log for 22

### Actual result

rule.Log is set to False for 20
rule.Log is set to False for 21
rule.Log is set to True for 22

Better would be to change
```
Rule {
	// If true, triggering this rule write to the error log
	Log bool
}
```
From bool to an enum.
NoLog -> Do not log the match
Log -> Log the match
Default  -> Fallback to default Log Action
indicating what was actually specified in the rule.

Without this information there is no way to know what was the intended behavior amongst 1000s of rules.

**Comment by jptosso** [comment]
Thank you @piyushroshan, seems like a real bug.  It could be an enum like you mentioned:

```go
const (
RuleLogDefault = iota
RuleNoLog = iota
RuleLog = iota
)
```

Still, I don't enjoy creating enum for something that is not widely used, the default could just be true. In that case we would only have to update directiveSecRule and force Log to true.

Other interesting thing we could do is create some SecDefaultActions like modsecurity does, so we hardcode into each compilation phase a set of default actions.

What do you think ? cc @bxlxx

**Comment by ShiMing-Q** [comment]
Vote for `SecDefaultAction`

**Comment by bxlxx** [comment]
> Vote for `SecDefaultAction`

I think so.
