### ISSUE TITLE
Implement new directive for performance profiling

### ISSUE THREAD

**Issue by bxlxx** [corazawaf/coraza#192]
### Summary

I think we need to add some hooks for the rule.

### Basic example

Not yet.

### Motivation

If we have some hooks of the rule, we can add some custom behaviors before and after rule execution. For example, collect the execution time of each rule(because our system performance requirements are high, it is necessary to do some observable work).

**Comment by jptosso** [comment]
@fzipi was motivated with this last year, I think we should think about a profiling engine for Coraza capable of creating a detailed report of the performance of the rule. There might be a way to attach ourselves to the profiling API and hook some "tags" https://pkg.go.dev/runtime/pprof

**Comment by jptosso** [comment]
> Sounds awesome!
> 
> Maybe makes sense also to have a `SecProfilingEngine <On|Off>`?

It sounds consistent with other directives like SecAuditEngine and SecRuleEngine.

**Comment by bxlxx** [comment]
This is still happening.
