### ISSUE TITLE
WAF sync mutex is not used

### ISSUE THREAD

**Issue by jptosso** [corazawaf/coraza#194]
WAF sync mutex is not used, so it should be removed. Is there any use we can give it ? or should it just go? 

```go
	RequestBodyNoFilesLimit int64

	// Used by some functions to support concurrent tasks
	mux *sync.RWMutex

	RequestBodyLimitAction types.RequestBodyLimitAction

	ArgumentSeparator string
```

**Comment by bxlxx** [comment]
> WAF sync mutex is not used, so it should be removed. Is there any use we can give it ? or should it just go?
> 
> ```go
> 	RequestBodyNoFilesLimit int64
> 
> 	// Used by some functions to support concurrent tasks
> 	mux *sync.RWMutex
> 
> 	RequestBodyLimitAction types.RequestBodyLimitAction
> 
> 	ArgumentSeparator string
> ```

It doesn't look like it's being used and should be added when it's used.

**Comment by bxlxx** [comment]
#188

**Comment by fzipi** [comment]
@bxlxx What happened to the PR for removing this? It was mixed with other stuff, but I guess you can add it now, right?

**Comment by bxlxx** [comment]
> @bxlxx What happened to the PR for removing this? It was mixed with other stuff, but I guess you can add it now, right?

Yeah! I'm working on it. Don't worry!
