### ISSUE TITLE
unmarshal array json in body

### ISSUE THREAD

**Issue by raszia** [corazawaf/coraza#203]
## Description

when i use tx.ProcessRequestBody() and my body request is an array json like this:
[{"name":"confluence.page.reading","properties":{"pageID":"111111"},"timeDelta":0}]
i get Interruption and in tx.Logdata i have this message:
json: cannot unmarshal array into Go value of type map[string]interface {}"

**Comment by bxlxx** [comment]
Thank you for your feedback. What are the rules you use?

**Comment by raszia** [comment]
i use coreruleset, but the error is from this func: 
func (js *jsonBodyProcessor) Read(reader io.Reader, _ Options) error {}
in this directory:
/home/ras/go/pkg/mod/github.com/corazawaf/coraza/v2@v2.0.0-rc.3/bodyprocessors/json.go
in this line:
fields, err := jsonToMap(data)

**Comment by jptosso** [comment]
This was fixed in #205 

Thank you for your report.
