### ISSUE TITLE
remove the logger field in the waf structure

### ISSUE THREAD

**Issue by bxlxx** [corazawaf/coraza#204]
I thought that maybe not need the logger field in the waf structure. There are two reasons for this:
1. coraza as a lib, the debug information is only applicable to the development or debugging stage, the error information should be thrown to the upper-level calling function, and finally, the user will handle the error information. 
2. If the user uses a non-zap log library and sets the log storage location, the log information in the production or test environment will not include the log printed by coraza, and the behavior of coraza's printing log information is meaningless.

**Comment by jptosso** [comment]
Also, the logging is just there to comply with SecDebugLog, maybe we can ask the implementor to provide a channel to send logs

**Comment by bxlxx** [comment]
Sorry, I forgot the ```SecDebugLog``` directive.
