### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by jptosso** [corazawaf/coraza#207]
I'm not a windows fan, but should we start thinking about windows compatibility? Most internal components are hardcoding "/" instead of the OS Path Separator. We also hardcode paths like /tmp and /dev/null.

**In order to achieve this, we should consider:**

- Replace all hardcoded and configured paths to ```filepath.FromSlash("/some/path")```
- Replace ```/tmp``` with ```os.TempDir()```
- Replace the pipes from ```/dev/null``` to ```ioutil.Discard```
- Anything else?
- Add Windows regression target github actions

Is it worth the effort? Should it be on our roadmap? Should we add windows support as a development requirement? Is this a v3 issue? I think it would only take a few hours to implement this

We can confirm this feature is working if all regression and CRS tests pass on windows.

**Comment by cts2021** [comment]
good feature！

**Comment by jptosso** [comment]
Closed at it requires a code owner for Windows products.
