### ISSUE TITLE
Tinygo support

### ISSUE THREAD

**Issue by jcchavezs** [corazawaf/coraza#210]
## Summary

Tinygo is desirable as it would open doors for delivering coraza features in embedded runtimes like wasm. Currently tinygo has a set of limitations in terms of support of stdlib and hence we need to decide if we want to support tinygo as a first class or shall we be able to deliver tinygo integration (which requires coraza to be more flexible)

Notably, libraries like `encoding/xml` isn't supported and there is no easy replacement for it.

### Motivation

Provide coraza as a wasm plugin for envoy.

**Comment by jptosso** [comment]
The changes were approved in the last meeting. 

Please try to compile Coraza removing JSON and XML support and we will use that as a starting point.

## Project requirements

1. Build constraints, we should add special building tags, so tinygo support doesn't mess with standard go.
For tinygo we would have to run 
```sh
tinygo build -tags tinygo *.go
```

And files with compatibility issues must have multiple versions, for example:
```go
// bodyprocessors/json_tinygo.go
// build: +tinygo
package bodyprocessors

include json"github.com/buger/jsonparser"
//...
}
```

```go
// bodyprocessors/json.go
// build: !tinygo
package bodyprocessors

include "encoding/json"
//...
}
```

2. Tests must be created for tinygo building and CRS compatibility

Under development

**Comment by jcchavezs** [comment]
I am curious on why this has been closed and I have no option to reopen it. Sounds like a mistake.

**Comment by jptosso** [comment]
Already merged
