### ISSUE TITLE
In case of `SecRuleEngine DetectionOnly` the intervention call gives back a NULL (nil)

### ISSUE THREAD

**Issue by airween** [corazawaf/coraza#233]
## Description

I reproduced this issue with libcoraza. When I call the function `coraza_intervention()`, and the `SecRuleEngine` has set to `DetectionOnly`, then function returns NULL (nil).

### Steps to reproduce

```
SecRuleEngine DetectionOnly

SecRule REMOTE_ADDR "127.0.0.1" "id:1,phase:1,deny,status:403"
```
send a request to localhost:

```
curl -v "http://localhost"
```

### Expected result

`coraza_intervention()` should return with an `intervention` object, not `nil`.

### Actual result

`coraza_intervention()` returns with `nil`.

**Comment by jptosso** [comment]
I think this design is suitable for golang design paradigms. What do you think, @fzipi?

Still, this should be patched for libcoraza to simulate ModSecurity's behavior.

**Comment by jptosso** [comment]
Closed at it will have a different behavior for libcoraza.,
