### ISSUE TITLE
Correct SecDebugLogLevel 6 in coraza.conf

### ISSUE THREAD

**Issue by sts** [corazawaf/coraza#252]
Debug levels documented in the coraza.conf-recommended are not correct: 
 https://github.com/corazawaf/coraza/blob/v2/master/coraza.conf-recommended#L204

Debug Level 6 is not available anymore: https://github.com/corazawaf/coraza/blob/f257ca6f6b11e7dfced0a6e8566c10fe3bdb3489/waf.go#L315

**Comment by jptosso** [comment]
You are right, they are configured for ZAP compatibility. This must be reviewed once we begin replacing ZAP for v3. In the meantime we can update the documentation.

**Comment by jcchavezs** [comment]
Is this still an issue? Worth to reopen? Cc @jptosso @M4tteoP

**Comment by M4tteoP** [comment]
I think so, to recap the current situation:
| [coraza.conf-recommended](https://github.com/corazawaf/coraza/blob/5408fcdf553217ea45ec9abda978e3fa593e663b/coraza.conf-recommended#L206-L217)  | Documentation | [Current implementation](https://github.com/corazawaf/coraza/blob/fce26f25ab3e1955de7b396d01d6b43dc8c33b7b/loggers/debug.go#L33) (v3/dev) |
| ------------- | ------------- | ------------- |
| 1: fatal<br>2: panic<br>3: error<br>4: warn<br>5: info<br>6: debug | 0: Fatal<br>1: Panic<br>2: Error<br>3: Warning<br>4: details of how transactions are handled<br>5: log everything |0: LogLevelUnknown<br>1: LogLevelInfo<br>2: LogLevelWarn<br>3: LogLevelError<br>4: LogLevelDebug<br>5: LogLevelTrace  |

We may have to: 
- Update the .conf-recommended accordingly.
- Reorder Error, Warning, Info. (From most verbose to least one: trace -> debug -> info -> warning -> error -> fatal, aren't they?)
- Update the doc? Is Fatal a Panic but with no log at all? 
- Agree on LogLevelUnknown. Currently, it is not a valid level for `LogLevel.Invalid()`, but wrong inputs are defaulting to it. Should we add a `LogLevelFatal` (at 0) and keep the `Unknown` for the wrong level?

**Comment by jcchavezs** [comment]
Wanna take a stab @M4tteoP ?
