### ISSUE TITLE
High memory usage with `coreruleset`

### ISSUE THREAD

**Issue by bkupidura** [corazawaf/coraza#253]
## Description

After loading all rules from `coreruleset` (https://coraza.io/docs/tutorials/coreruleset/), Coraza instance consumes 130MB.

From quick pprofing looks like issue is with `github.com/cloudflare/ahocorasick.(*Matcher).buildTrie`.

I wouldnt care, but nginx with modsecurity (modsecurity-crs docker image) is consuming 40MB with exact same ruleset.

Is there anything im missing?

### Steps to reproduce

Create Coraza instance based on https://coraza.io/docs/tutorials/coreruleset/

### Expected result

Much lower memory usage.

### Actual result

High memory usage :)

**Comment by jptosso** [comment]
Hey @bkupidura, can you share the whole pprofing file?

**Comment by bkupidura** [comment]
[pprof.alloc_objects.alloc_space.inuse_objects.inuse_space.002.pb.gz](https://github.com/corazawaf/coraza/files/8773001/pprof.alloc_objects.alloc_space.inuse_objects.inuse_space.002.pb.gz)

**Comment by jptosso** [comment]
<img width="632" alt="image" src="https://user-images.githubusercontent.com/1236942/170315721-9730773c-010b-4387-93a2-2e1eed39670d.png">

This is wrong, we will generate a discussion on this to replace aho-corasick ASAP

**Comment by jptosso** [comment]
Can you validate that you are testing against transactions? It seems you are validating the aho-corasick initialization:
<img width="857" alt="image" src="https://user-images.githubusercontent.com/1236942/170315951-c4606dd9-b51e-4dd3-bf5a-2133260e7d12.png">

The garbage collector should free the resources after no more than a second that the rules were compiled

**Comment by bkupidura** [comment]
High memory usage is constant, so looks like GC is not freeing those resources.

Here is very sample code, which behaves exactly same way - so you can check:

```
package main

import (
        "log"
        "net/http"

        _ "net/http/pprof"

        "github.com/corazawaf/coraza/v2"
        "github.com/corazawaf/coraza/v2/seclang"
)

var waf *coraza.Waf

func setupCoraza() error {
        waf = coraza.NewWaf()

        seclang, err := seclang.NewParser(waf)
        if err != nil {
                return err
        }

        files := []string{
                "coraza.conf",
                "coreruleset/crs-setup.conf.example",
                "coreruleset/rules/*.conf",
        }
        for _, f := range files {
                if err := seclang.FromFile(f); err != nil {
                        return err
                }
        }
        return nil
}

func main() {
        if err := setupCoraza(); err != nil {
                panic(err)
        }
        log.Fatal(http.ListenAndServe(":8080", nil))
}
```

**Comment by jcchavezs** [comment]
We can try different libraries, for example https://github.com/BobuSumisu/aho-corasick. See https://github.com/Bobusumisu/aho-corasick-benchmark.

**Comment by jptosso** [comment]
Fixed by replacing the aho corasick library
