### ISSUE TITLE
The rx operator doesn't support single byte matching

### ISSUE THREAD

**Issue by bxlxx** [corazawaf/coraza#270]
## Description

Due to the reason of golang itself, the regexp library doesn't support matching a single byte. (In the re2 sytax, ```\C```  support matching single byte)Reference: [go regexp](https://github.com/golang/go/blob/160414ca6a30a210b82fb09abbd3541802a51017/src/regexp/regexp.go#L10)

There are some rules in CRS that rely on matching a single byte. So We need to discuss this question, should we use another re2 library instead of the regexp or create a new plugin to support it?

**Comment by jptosso** [comment]
Is this fixed by using bytes instead of strings?

**Comment by jptosso** [comment]
This is still happening, we should track this for v3

**Comment by jptosso** [comment]
We are passing CRS tests, so it doesn't seem like a v3 problem.
