### ISSUE TITLE
SecAuditLog is not working

### ISSUE THREAD

**Issue by Mahboubi68** [corazawaf/coraza#275]
## Description

I used ModSecurity WAF (v2) and I can store or send its logs to a remote Syslog server with the following configs:
SecAuditLog /var/log/audit.log
SecAuditLog "|/usr/bin/socat - TCP4:172.16.1.1:1234"

But in Coraza WAF (I'm using its docker image) the mentioned configs are not working. Actually, if I store the logs generated by rules in a log file, it won't work, the log file is always empty. And also if I use the second config to send my logs to a remote Syslog server, the docker container is not started. (Actually, I installed the socat package inside the image before running it as a container) I'm using the following docker image:
https://hub.docker.com/r/jptosso/coraza-waf

### Steps to reproduce

SecAuditLog /var/log/audit.log
SecAuditEngine RelevantOnly
SecAuditLogRelevantStatus "^(?:(5|4)(0|1)[0-9])$"

OR

SecAuditLog "|/usr/bin/socat - TCP4:172.16.1.1:1234"
SecAuditEngine RelevantOnly
SecAuditLogRelevantStatus "^(?:(5|4)(0|1)[0-9])$"

### Expected result
writing logs into the /var/log/audit.log file
OR
sending logs to a remote server

### Actual result

There is no log.

**Comment by jptosso** [comment]
Hey @Mahboubi68 thank you for your report. We are not currently supporting a docker container for the Coraza core, there is just an experimental docker image for coraza-caddy that requires an update, as the caddy project doesn't currently have a maintainer.

There is an upcoming project to support coraza-spoa for docker: https://github.com/corazawaf/coraza-spoa/pull/23

Regarding the socat usecase, it is actually not implemented, we will keep this issue to add support for `|/usr/bin/socat`

**Comment by Mahboubi68** [comment]
Thanks a lot for your answer

**Comment by sts** [comment]
@Mahboubi68 What docker image did you use? Let us know if you had success with the haproxy (coraza-spoa) image.

**Comment by Mahboubi68** [comment]
Dear @sts, I found only one coraza image in docker hub repository named coraza-caddy. As @jptosso said, it is experimental.
https://hub.docker.com/r/jptosso/coraza-caddy
I used coraza-spoa docker file and built its image, but I don't know how to run the container. What are the arguments in run time:
docker run -it image_name ......
I hope you release your final docker images (with Apache or Nginx web server) in the docker hub repository.

**Comment by jptosso** [comment]
We are currently struggling with connectors support. Most users are using coraza as a library. 

Thankfully @sts is contributing a lot on coraza-spoa, so I think it will be the first connector to become stable soon. 

We are currently focused on coraza v3, so I don't think there will be significant changes until we release a stable v3 tag, but this is definitely a priority in our roadmap.

**Comment by sts** [comment]
@Mahboubi68 Instructions are in the README of my branch: https://github.com/sts/coraza-spoa/tree/docker#docker

There is a [docker-compose.yaml](https://github.com/sts/coraza-spoa/blob/docker/docker-compose.yaml) included, which launches haproxy, coraza, and a mockserv application, which you can simply replace by your own application or rather point the haproxy backend to an application servers ip address.

**Comment by Mahboubi68** [comment]
@jptosso and @sts Tnx a lot for the explanation

**Comment by jessequinn** [comment]
> Hey @Mahboubi68 thank you for your report. We are not currently supporting a docker container for the Coraza core, there is just an experimental docker image for coraza-caddy that requires an update, as the caddy project doesn't currently have a maintainer. (see https://hub.docker.com/r/jptosso/coraza-caddy)
> 
> There is an upcoming project to support coraza-spoa for docker: [corazawaf/coraza-spoa#23](https://github.com/corazawaf/coraza-spoa/pull/23)
> 
> Regarding the socat usecase, it is actually not implemented, we will keep this issue to add support for `|/usr/bin/socat`

@jptosso i am not sure if i get your response. Coraza does not support SecAuditLog or it does? this is independent of Docker or not.

**Comment by jptosso** [comment]
It does support SecAuditLog, but it doesn't support PIPE CMD commands, still, it will be implemented.
