### ISSUE TITLE
Drop Transaction.ProcessRequest

### ISSUE THREAD

**Issue by jcchavezs** [corazawaf/coraza#283]
## Summary

I'd like to propose to drop `Transaction.ProcessRequest` from the `coraza` package (see https://github.com/corazawaf/coraza/blob/ddbce89245135ea7243ff1b5399ec2ac786479e9/transaction.go#L452). The reason is that it is too specific and makes assumptions about the usage of the library in the core package. Ideally this kind of specific helpers should go to another package or be an example.

On a side not, `net/http` package isn't supported by `tinygo` making this inconvenient, that was my original motivation for this request but if I could ignore this function in tiny_go, I believe this is a too specific function.

cc @jptosso @fzipi

**Comment by jptosso** [comment]
I agree with moving this function and all transaction helpers to another package, like coraza/v3/utils/http

**Comment by jptosso** [comment]
Implemented in v3 https://github.com/corazawaf/coraza/pull/296
