### ISSUE TITLE
Transaction.ProcessRequest() EOF on large requests

### ISSUE THREAD

**Issue by DrewStratford** [corazawaf/coraza#284]
## Description

When using `Transaction.ProcessRequest()` on large requests, coraza replaces the request body with a temporary file and then reads from this file to process the rules. This means that after `ProcessRequest()` completes, the file position is at the end, so any further reads from the request body will return an EOF.

This is not an issue for small requests as `BodyBuffer.Reader()` returns a new byte reader.

### Steps to reproduce
In your rules file: set `SecRequestBodyAccess On` and create a rule to examine the body.

Create a http request with a body greater than `requestBodyInMemoryLimit` (128 KiB by default). Call `Transaction.ProcessRequest()` on that request. After the `ProcessRequest` completes the request will be at the end of the file

### Expected result

After the the call to `ProcessRequest` the position should be at the start of the file.

### Actual result

The position is at the end of the file.

**Comment by jptosso** [comment]
Hey @DrewStratford  thank you for your report.

Are you trying to reuse the http reader after consuming it?

By definition all readers will be emptied after being read, in case of Coraza connector, what we do is we replace the pointers, for example:

```go
body := req.Body
io.Copy(tx.RequestBodyBuffer, req.Body)
reader, _ := tx.RequestBodyBuffer.Reader()
// Then we hack the body with:
req.Body = io.NopCloser(reader)
```

**Comment by DrewStratford** [comment]
Hi @jptosso,

I'm using a `ProcessRequest` programmatically. For the meantime, I'll use `br.Reader()` to reset the file position.

One potential solution is, in `BodyBuffer.Reader`, re open the writer using something like `os.Open(br.writer.Name())`. The new file would have a separate position. The problem with this though is that now you'd have manage all the extra file descriptors.

**Comment by jptosso** [comment]
The problem with opening new file readers is that a user won't have the chance to close it, as it is a reader and not a file. We would have to store a list of open files and close them in the future, but that is memory expensive.

**Comment by jcchavezs** [comment]
Ping @anuraaga

**Comment by jptosso** [comment]
We should add more documentation on this, but this is expected behavior.
