### ISSUE TITLE
Use assert library for tests

### ISSUE THREAD

**Issue by jcchavezs** [corazawaf/coraza#297]
## Summary

Tests can be simplified and more readable by the usage of the `assert` library. See https://github.com/stretchr/testify.

### Basic example

For example in https://github.com/corazawaf/coraza/blob/v2/master/seclang/rules_test.go#L351

```go
if tx.IsProcessableResponseBody() {
	if _, err := tx.ResponseBodyBuffer.Write([]byte("#!/usr/bin/python")); err != nil {
		t.Error(err)
	}
	it, err := tx.ProcessResponseBody()
	if err != nil {
		t.Error(err)
	}
	if it != nil {
		httpOutMsg := ""
		for _, res := range tx.MatchedRules {
			httpOutMsg = httpOutMsg + res.MatchedDatas[0].Key + ":" + res.MatchedDatas[0].Value + "\n"
			httpOutMsg = httpOutMsg + "Message:" + res.MatchedDatas[0].Message + "\n"

		}
		if len(httpOutMsg) == 0 || len(tx.MatchedRules) == 0 {
			t.Error("failed to log")
		}
	} else {
		t.Error("failed to block response body")
	}
} else {
	t.Error("failed to process response body")
}
```

can become 

```go
require.False(t, tx.IsProcessableResponseBody(), "failed to process response body")

_, err := tx.ResponseBodyBuffer.Write([]byte("#!/usr/bin/python")); 
assert.NoError(t, err)

it, err := tx.ProcessResponseBody()
assert.NoError(t, err)

require.NotNil(t, it, "failed to block response body")

httpOutMsg := ""
for _, res := range tx.MatchedRules {
	httpOutMsg = httpOutMsg + res.MatchedDatas[0].Key + ":" + res.MatchedDatas[0].Value + "\n"
	httpOutMsg = httpOutMsg + "Message:" + res.MatchedDatas[0].Message + "\n"

}

assert.True(t, len(httpOutMsg) == 0 || len(tx.MatchedRules) == 0, "failed to log")
```

Include a basic example or links here.

### Motivation

Went through test and we have a lot of boilerplate to do assertions.

**Comment by fzipi** [comment]
Way more readable, for sure!

**Comment by fzipi** [comment]
I don't mind, but we should move all our tests if we do this, and be consistent. Also, add pointers and documentation so others use the same.

**Comment by jcchavezs** [comment]
I feel like we could do this in v2 (given that tests are green there) but not sure how much work will it be to rebase onto v3/dev tho it does not look like a lot of work https://github.com/corazawaf/coraza/compare/v2/master...v3/dev

**Comment by jptosso** [comment]
Don't worry about the rebase, we haven't touched tests yet

**Comment by jcchavezs** [comment]
Ok, I will do that in v2/master then.
