### ISSUE TITLE
Add ability to run development commands like formatting

### ISSUE THREAD

**Issue by anuraaga** [corazawaf/coraza#313]
Currently there isn't any central definition of development commands for this repo, such as linting and formatting. It would be easier to contribute if there were.

I personally like magefile (used by hugo) since it works smoothly on Windows and doesn't require learning new syntax

https://magefile.org/zeroinstall/

But Makefile is also popular so would be fine too.

If this sounds helpful, I can contribute a PR.

**Comment by jcchavezs** [comment]
+1 on this. I think at the beginning it made sense to keep this simple and
depend on go toolchain only. However now that we are supporting more stuff
(tinygo, wasm, building examples) makes sense to have an structures for
commands. As for lint I'd like to use golangci command, also declaring all
the tooling with proper versioning in a go module (e.g. using build tag
`tools`).

As for the tool, I only used make and I think when keeping it simple it is
very easy to use but I. Also open to other alternatives (cc @jptosso)

**Comment by jptosso** [comment]
Merged https://github.com/corazawaf/coraza/pull/315
