### ISSUE TITLE
Custom URL encoded processor

### ISSUE THREAD

**Issue by jptosso** [corazawaf/coraza#325]
The custom URL processor must consider the [RFC3986](https://www.ietf.org/rfc/rfc3986.txt)

A few additional details:
- Decoding is non-strict: [See Modsecurity](https://github.com/SpiderLabs/ModSecurity/blob/4127c1bf52d2b30a5c2c3e641b8085fd9a720f43/src/utils/decode.cc)
- There will be no exceptions, all URLs are valid. What to do with binary data?
- We must only support the `&` separator
- We must ignore the anchor part 
- We must have a huge set of tests for this, this is very sensitive
- For normalization, invalid urlencoded characters must be printed in form %YZ
- Ranges (0-9, A-F) are not suported and must be printed in %FF form

```
         foo://example.com:8042/over/there?name=ferret#nose
         \_/   \______________/\_________/ \_________/ \__/
          |           |            |            |        |
       scheme     authority       path        query   fragment
          |   _____________________|__
         / \ /                        \
         urn:example:animal:ferret:nose
```

**Comment by jcchavezs** [comment]
Could you elaborate on the need for this and what are the cases?

**Comment by jptosso** [comment]
There are tens of CRS tests not passing because Coraza reads the URL with a strict filter and denies the request returning URL encoded error.

The new version of the decoder does the exact same as the golang decoder, but if a character is invalid, it just prints it literally, for example: 
`% A`  = `% A`
`%20%` = ` %`
`%ZZ` = `%ZZ`

All of the previous cases would have returned error using the golang filter.

**Comment by jcchavezs** [comment]
![image](https://user-images.githubusercontent.com/3075074/188689049-5fa70114-cc84-40a0-a3e0-f8795d7703d1.png)

https://twitter.com/bagder/status/1567162794092404742
