### ISSUE TITLE
Allow custom debug logger implementation

### ISSUE THREAD

**Issue by anuraaga** [corazawaf/coraza#330]
## Summary

Allow a custom `DebugLogger` implementation

### Basic example

```go
type envoyDebugLogger {}

func (l *envoyDebugLogger) Info(message string, args ...interface{}) {
  proxywasm.LogInfof(message, args...)
}
```

### Motivation

We would like debug logs to go to Envoy logs when loading coraza as a wasm filter. Currently `DebugLogger` is a struct and can only direct logs to `log.Logger`, it would be nice if it were an interface that can have the current implementation or a custom one. @jptosso does this sound reasonable?

**Comment by jptosso** [comment]
Merged https://github.com/corazawaf/coraza/pull/337
