### ISSUE TITLE
Allow using a BodyBuffer not backed by a file for wasm

### ISSUE THREAD

**Issue by anuraaga** [corazawaf/coraza#331]
Currently `BodyBuffer` includes code that writes to a file. This code currently cannot be compiled and used in wasm (even if the code isn't executed) because it will try to import functions for accessing filesystem which don't exist, at least yet. Specifically, it is `os.Remove` that is not available or stubbed.

Unfortunately because this is a code compilation issue, I don't think it would be fixed by having an interface that the code switches based on something like an option, since the code paths would be compiled anyways. Would it be reasonable to have normal and tinygo versions of `BodyBuffer` separated by build tag, with the latter not supporting file storage?

**Comment by jptosso** [comment]
Fixed in v3 https://github.com/corazawaf/coraza/pull/332
