### ISSUE TITLE
Monthly meeting agenda (August 2022)

### ISSUE THREAD

**Issue by jptosso** [corazawaf/coraza#351]
- **Date:** [_Wednesday, August 31 at 12 p.m. UTC_](https://dateful.com/convert/utc?t=12pm&d=2022-08-31)
- **Previous agenda:** https://github.com/corazawaf/coraza/issues/267

> July agenda was a v3 general review. It wasn't documented.

### Current agenda
1. General project status
2. Performance report: v2/v3/modsecurity
3. v2 status
   - v3 -> v2 cherry picking
   - v2.0.2 milestones
4. v3 status
   - WASM support @jcchavezs 
   -  https://github.com/corazawaf/coraza/issues/336
   - v3 bug bash https://github.com/corazawaf/coraza/discussions/377
5. New features and discussions
   - ~~https://github.com/corazawaf/coraza/issues/349~~ + PM suricata syntax @jptosso 
   - Rate limiting: new operator, new action, or new specific rule? @fzipi 
   - https://github.com/corazawaf/coraza/issues/372 @anuraaga 
   - https://github.com/corazawaf/coraza/issues/373 @anuraaga 
   - https://github.com/corazawaf/coraza/issues/374 @anuraaga 
   - https://github.com/corazawaf/coraza/issues/371 @anuraaga 
   - Marketing: blog posts, videos, medium, company posts, OWASP @jptosso 

### Pending discussions
- GraphQL response body processor
- Persistence

### How to join?
1. Join OWASP slack: https://owasp.org/slack/invite
9. Join the #coraza channel: https://owasp.slack.com/archives/C02BXH135AT

**Comment by nacx** [comment]
Thanks for putting this together! I already missed some meetings and wondered if it would be possible to create a Coraza public Google Calendar or something similar we could subscribe to to get those nice notifications and reduce the chances of missing it. Thx!

**Comment by fzipi** [comment]
@nacx Created [coraza public calendar](https://calendar.google.com/calendar/ical/c_s1vf6auene1ehionfslv010tk8%40group.calendar.google.com/public/basic.ics)
