### ISSUE TITLE
Technical debt v3

### ISSUE THREAD

**Issue by jptosso** [corazawaf/coraza#362]
We should try to release v3 without technical debt.

- [ ] Move most types to the types package and sub-packages
- [ ] Replace hardcoded strings and ints with well-documented constants
- [ ] Custom error types
- [ ] Add detailed documentation for each package
- [ ] Refactor the Rule evaluation algorithm by creating a `ruleEval` struct
- [ ] Reduce code complexity of modsecurity inherited transformations. For example, this is a C port to golang: https://github.com/corazawaf/coraza/blob/v2/master/transformations/url_decode_uni.go

**Comment by jcchavezs** [comment]
- Move monolitic testdata to consumer package

**Comment by jcchavezs** [comment]
> Reduce code complexity of modsecurity inherited transformations

Would you elaborate a bit more on this?

**Comment by jptosso** [comment]
> > Reduce code complexity of modsecurity inherited transformations
> 
> Would you elaborate a bit more on this?

I have quoted a sample code: https://github.com/corazawaf/coraza/blob/v2/master/transformations/url_decode_uni.go

Basically, there is C code ported to golang. We should make it the golang way
