### ISSUE TITLE
Embed core rule set

### ISSUE THREAD

**Issue by anuraaga** [corazawaf/coraza#372]
It would be a magical experience if `coraza.NewWaf()` with no configuration produced a waf that is fairly usable. We could add a git submodule to CRS and `go:embed` it as the default rules when nothing is provided. This would add a bit of size to compiled apps but I think the rules aren't big enough to be too concerned while providing a very convenient API, especially for users that are just getting started with WAF (like me :D)

**Comment by fzipi** [comment]
🤔 I would not force people to have the CRS unless we want to have two different compile options.

**Comment by anuraaga** [comment]
opt-in or opt-out can be something to think about for sure. Even if the default isn't a waf with rules, if it's just one knob to enable it that could still be quite nice for people getting started.

**Comment by jptosso** [comment]
https://github.com/jptosso/crsmon

**Comment by anuraaga** [comment]
Per discussion, It makes sense for this to be an aspect of the UX, e.g. caddy or envoy integrations. The core engine is likely not a place to embed rules like CRS.
