### ISSUE TITLE
There is no implementation for the `allow` action

### ISSUE THREAD

**Issue by fzipi** [corazawaf/coraza#395]
## Description

```
func (a *allowFn) Evaluate(r *coraza.Rule, tx *coraza.Transaction) {
	// TODO implement this:
	/*
		if a.allow == 1 {
			tx.RuleEngine = coraza.RULE_ENGINE_OFF
		} else if a.allow == 2 {
			//tx.SkipToPhase = tx.LastPhase +1
		} else if a.allow == 3 && tx.LastPhase < 3 {
			//tx.SkipToPhase = 3
		}
	*/
}
```

This **MUST** be implemented.

### Steps to reproduce

Probably adding one rule that allows first, and then blocking it will result in blocking.

### Expected result

It should be allowed.

### Actual result

Well, guess.

**Comment by jcchavezs** [comment]
Wanna take a stab @M4tteoP?

**Comment by fzipi** [comment]
#527 should implement this, but we are trying to move stuff to `internal` before.
