### ISSUE TITLE
Rename coraza.conf-recommended to coraza-recommended.conf?

### ISSUE THREAD

**Issue by anuraaga** [corazawaf/coraza#401]
Very small issue, but if it's the recommended configuration I guess it's meant to be used as is. In that case, does it make sense to make sure it has a `.conf` extension like other rules?

**Comment by jptosso** [comment]
> I think it is from the ModSecurity convention (`modsecurity.conf-recommended` file). I always interpreted it as a way of raising users' awareness asking them as a first step to rename it to `.conf` and customize it accordingly to their needs. From [ModSec perspective](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v3.x%29#a-recommended-base-configuration:~:text=are%20the%20items%20that%20the%20Admin%20should%20handle%20and%20configure%20for%20their%20own%20site), it is more a recommended list of things that have to be configured rather than a recommended configuration to be used as is. I don't know if Coraza's one is intended in a different way.

Same reason, although you can import the file as coraza.con-recommended, the idea is to tell the user to rename the file so they read it and change the settings

**Comment by anuraaga** [comment]
Got it, makes sense
