### ISSUE TITLE
Refactor RuleMatch

### ISSUE THREAD

**Issue by jptosso** [corazawaf/coraza#407]
We currently generate the audit logs (errors with matched data) and error logs (errors without matched data) using the status code as a parameter.

modsecurity-nginx uses `msc_update_status_code` to set the transaction status.

The common problem that we get is, that we don't often know the status of the transaction during this phase, for example, coraza-caddy will receive the log callback, and it won't have access to the transaction or the request object.

To solve this, ModSecurity sends the log callback to each transaction, that way, each transaction can report its status code.

Maybe we should remove the status parameter and assume the transaction status variable is valid?

**Comment by anuraaga** [comment]
I noticed this when writing the wasm filter which had the same issue. Indeed removing the status code from that method sounds good.
