### ISSUE TITLE
Transaction Context usage

### ISSUE THREAD

**Issue by jptosso** [corazawaf/coraza#417]
We haven't found a real-world use case for transaction context. Could we discuss some ideas? Otherwise, we might have to remove it.

**Comment by jptosso** [comment]
My only use-case is RBL, as it uses channels to recover the DNS package

**Comment by anuraaga** [comment]
I haven't thought through completely, but one thing to keep in mind is `context` is often a way to propagate information opaquely from known components with an unknown bridge. So e.g., if I own entrypoint, and custom directive plugin, but don't own Coraza itself, if I need a way to get data from entrypoint to plugin, context can be a nice way to do it (every `Process` method should accept context, not just `NewTransaction` as now.

Also if there is any potential to have directives or rules that make actual external API calls (rate limiting directive pulling rules from somewhere?) then propagating context is important for observability of the external calls.

Just a couple of things that come to mind

**Comment by jcchavezs** [comment]
I think @anuraaga's ideas are valid but I think there are many things that have to happen before we do it. For example, the external call makes total sense if we can cancel the context which should come with the limitations described above.

The information propagated is also a good idea but I think we need to complete the refactor to finally come up with a design for this.

My proposal is that we remove the existing context in the transaction and we revisit this in v4.
