### ISSUE TITLE
NewTransaction panic

### ISSUE THREAD

**Issue by huhuegg** [corazawaf/coraza#429]
## Description

strings.RandomString panic

### Steps to reproduce

tx := waf.NewTransaction(context.Background())

### Actual result

```
panic: runtime error: index out of range [-2]

goroutine 90456973 [running]:
math/rand.(*rngSource).Uint64(...)
	/usr/local/go/src/math/rand/rng.go:249
math/rand.(*rngSource).Int63(0x0?)
	/usr/local/go/src/math/rand/rng.go:234 +0x92
github.com/corazawaf/coraza/v3/internal/strings.RandomString(0x13)
	/root/go/pkg/mod/github.com/corazawaf/coraza/v3@v3.0.0-20220914101451-05d352c89b24/internal/strings/strings.go:30 +0x133
github.com/corazawaf/coraza/v3.(*WAF).NewTransaction(0xc002c82820, {0x297?, 0x2c0?})
	/root/go/pkg/mod/github.com/corazawaf/coraza/v3@v3.0.0-20220914101451-05d352c89b24/waf.go:146 +0x5f
```

**Comment by jptosso** [comment]
Thank you for your report!

CC @anuraaga

**Comment by jcchavezs** [comment]
What version of Go are you using?

**Comment by jcchavezs** [comment]
I was looking at https://github.com/golang/go/blob/go1.18.3/src/math/rand/rand.go#L41-L42 and it seems this is not concurrent safe and this is not suitable for http server environments (in which case we spawn one goroutine per request). Maybe we want to have a different implementation depending on build tag. cc @anuraaga

**Comment by anuraaga** [comment]
Yup this was a miss, will switch to making it concurrent safe, it's not worth a build tag I think

**Comment by jptosso** [comment]
We should also add concurrency tests to CI

**Comment by anuraaga** [comment]
Thanks a lot for the report @huhuegg and sorry for the troubles, should be fixed on the latest commit now
