### ISSUE TITLE
relative import when using `systemctl start caddy.service`

### ISSUE THREAD

**Issue by Saperlu** [corazawaf/coraza#431]
## Description

I can't currently paste logs  but it says that no sites-enabled directory or file was found.

### Steps to reproduce

 put this in `/etc/caddy/Caddyfile` : `import sites-enabled/*`
`cd <elsewhere_than_/etc/caddy>`
`systemctl start caddy.service`

### Expected result

Should import files of directory

### Actual result

Fails.

### Solution proposed

Well, I don't know where is the code of the package so I make an issue on this repo. Hopefully you can edit the file that comes in `/lib/systemd/system/caddy.service` on debian.

To patch it, I simply did `systemctl edit caddy.service` and then input this : 
```
[Service]
WorkingDirectory=/etc/caddy
```

**Comment by jptosso** [comment]
Hey @Saperlu, it seems like your report is related to https://github.com/caddyserver/caddy and not to Coraza, as we don't ship any systemd service.

In the meantime, I suggest you use absolute paths (`import /etc/caddy/sites-enabled/*`

**Comment by jptosso** [comment]
no problem, the link to the code you are looking for is here: https://github.com/caddyserver/dist/blob/master/init/caddy.service so you can write a PR :)
