### ISSUE TITLE
CRS compatibility github action

### ISSUE THREAD

**Issue by jptosso** [corazawaf/coraza#436]
V3 compatibility with CRS varies from PR to PR. We should have a mechanism to keep track of compatibility and maintain regression.

We could write a GitHub action to write CRS compatibility and post comments to PR like:

-------------------------------

OWASP Core Ruleset (TAG_HASH) FTW rules were executed in 19.86s

Passed Tests: ✅1000/:x:1020 (98,03%)
Failed Tests: 00000-0, 111111-0

**Comment by anuraaga** [comment]
FYI we're working on this feature in ftw which should help with this

https://github.com/fzipi/go-ftw/issues/78
