### ISSUE TITLE
Text/plain or custom Content-Type bypasses body evaluation.

### ISSUE THREAD

**Issue by M4tteoP** [corazawaf/coraza#438]
## Description
POST requests with an explicit Content-Type header equal to `text/plain` or even just an empty space lead to not analyzing the body and directly sending it to the server.
I'm running a Coraza instance with a simple rule that checks the request body against a string (`maliciouspayload`):
```
...
SecRequestBodyAccess On
SecRule REQUEST_BODY "@rx maliciouspayload" "id:102,phase:2,t:lowercase,deny"
...
```
Curl requests like the followings, with explicit Content-Type different than `application/x-www-form-urlencoded` are leading to not checking the body:
- `curl -i -X POST -H 'Content-Type: text/plain' 'http://localhost:8090' --data "maliciouspayload"`
- `curl -i -X POST -H 'Content-Type: ' 'http://localhost:8090' --data "maliciouspayload"`

Logs:
```
[Evaluating phase 2
[[102] Evaluating rule 102
[[102] Expanding 1 arguments for rule 102
[[102] Transforming argument "" for rule 102
[[102] Arguments transformed for rule 102: []
[[102] Evaluating operator "@rx maliciouspayload" against "": NO MATCH
[[102] Finish evaluating rule 102
[Finished phase 2
```
`"@rx maliciouspayload" against "": NO MATCH` particularly caught my eye, meaning that the evaluation is performed, but against an empty string.

While, with `application/x-www-form-urlencoded`, the body is evaluated and the request is denied: 
- `curl -i -X POST -H 'Content-Type: application/x-www-form-urlencoded' 'http://localhost:8090' --data "maliciouspayload"`

Logs:
```
Attempting to process request body using "URLENCODED"
Evaluating phase 2
[102] Evaluating rule 102
[102] Expanding 1 arguments for rule 102
[102] Transforming argument "maliciouspayload" for rule 102
[102] Arguments transformed for rule 102: [maliciouspayload]
[102] Matching rule 102 REQUEST_BODY:
[102] Evaluating action log for rule 102
[102] Evaluating action auditlog for rule 102
[102] Evaluating action t for rule 102
[102] Evaluating operator "@rx maliciouspayload" against "maliciouspayload": MATCH
[102] Disrupting transaction by rule 102
[102] Evaluating action deny for rule 102
rule 102 matched
```

### Steps to reproduce
Curl commands above against [this branch](https://github.com/M4tteoP/coraza/tree/body-content-type-playground) (http-server example).

Is this an intended behaviour evaluating only super specific Content-Types? If so, shouldn't this behaviour be handled by the CRS rule 900220 that checks allowed Content-Types?

Thanks!

**Comment by jptosso** [comment]
Hey! Evaluation of content-types for urlencoded is only enforced if content-type is x-www-form-urlencoded or the CTL variable `ForceRequestBodyVariable` is set. Rule `900220` should stop an unknown content-type. I will look into it

**Comment by M4tteoP** [comment]
Hi @jptosso!
Just to specify:
- setting `application/x-www-form-urlencoded`  seems to actually be the only way to parse the body request.
- Speaking about `900220`, I was just thinking loud about CRS duties and Coraza ones, in the example, the CRS is NOT loaded.

I debugged a bit and seems that if no processing is done on the body, the latter is not added to the transaction. With https://github.com/corazawaf/coraza/pull/439 it is now working.  Could it make sense to have a generic `bodyprocessor` that just performs this option of populating the transaction and will performed with no other bodyprocessors are triggered Inside the (`if rbp == "" {`)?

Thanks for the help and feedbacks

**Comment by jptosso** [comment]
There is a design reason for that. There are many cases where we just want to avoid processing the body, mostly because of resources and DDOS. Specific pages, specific mimes, specific lengths.

We cannot accept all bodies by default, it must be custom tailored by the user according to his needs.

**Comment by M4tteoP** [comment]
I see, and I understand the reasoning behind the necessity of defining boundaries between analyzing it or not.
I'm just not so sure about the overall default behaviour.
By default:
- A request with a payload as simple as `text/plain` is not evaluated, but always allowed.
- A request with a payload with content type`application/x-www-form-urlencoded` is processed and (always?) evaluated.
- A request with any malformed content type is not evaluated, but always allowed.

Why should a user expect that a legit content type like `text/plain` is not being evaluated but `application/x-www-form-urlencoded` is? Currently bypassing a request-body rule is a matter of changing the content type to any value different than `application/x-www-form-urlencoded`. My mind is now getting trapped in a rabbit hole thinking that the only way to have this rule effective is indeed to enable `ForceRequestBodyVariable`. 😵‍💫

**Comment by jptosso** [comment]
You can also force the body processor by ctl: requestBodyProcessor=JSON, for example.

If you would like to expand this discussion, we could check it on tomorrow's meeting #388

**Comment by jcchavezs** [comment]
Just for context. What is modsec default behaviour?

**Comment by M4tteoP** [comment]
Writing down a recap about when the request body is evaluated:
1. First of all `RequestBodyAccess` requires to be `On`.
2. By default, with just `1.` the `REQUEST_BODY` variable is populated **only** if the content-type is `application/x-www-form-urlencoded`. Against any other content-type the variable will be empty and rules will never match.
3. We can force to populate the `REQUEST_BODY`:
   - via `ForceRequestBodyVariable`
   - Enforcing a specific body processor. E.g. `ctl:requestBodyProcessor=JSON`

Speaking about running the CRS:
- `3.` is basically enforced during the initialization by rule [`901340`](https://github.com/coreruleset/coreruleset/blob/v4.0/dev/rules/REQUEST-901-INITIALIZATION.conf#L332).
- Content-type manipulation is mitigated by [`900220`](https://github.com/coreruleset/coreruleset/blob/ac4e025d5ef41904c1880f5f3769e0d4de4eb041/crs-setup.conf.example#L466) where it is possible to explicit the list of allowed content types.


To the best of my knowledge, ModSecurity:
- **v2**:  Behaves just like described above ([Manual ref](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#request_body)). (Not personally tested)
- **v3**: Always populates the REQUEST_BODY therefore by default any content-type leads to analyze the body ([ref](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v3.x)#ctl)). (tested)

If we are on the same page about the described behaviour I would close this issue and propose to just merge @jcchavezs's PR https://github.com/corazawaf/coraza/pull/441.

**Comment by jcchavezs** [comment]
Is this still an issue @M4tteoP?

**Comment by M4tteoP** [comment]
I think that we somewhat agreed that the behaviour described in the [previous comment](https://github.com/corazawaf/coraza/issues/438#issuecomment-1276335416)) is the intended one. So, unless new considerations are made, we can keep this issue closed
