### ISSUE TITLE
Consolidate actions, operators, transformations to seclang package

### ISSUE THREAD

**Issue by anuraaga** [corazawaf/coraza#447]
From what I understand, actions operators and transformations are mechanisms to register functionality to strings that are used when processing seclang directives. If this is a correct understanding, would it make sense to consolidate the three under a package called `seclang`? Or otherwise maybe the `rules` package? It's not a real issue but something that could make the organization of functionality easier to understand when reading docs

**Comment by jptosso** [comment]
The original idea was to keep everything away from seclang so coraza could be extended to different languages using the same operators and transformations. It doesn't look that it will happen anytime soon though.

We should create a final api normalization session to close not this one but all open api definition issues.
