### ISSUE TITLE
V3 coverage improvement

### ISSUE THREAD

**Issue by jptosso** [corazawaf/coraza#453]
Current coverage is 80%. We should aim at 100%.

https://app.codecov.io/gh/corazawaf/coraza/tree/v3%2Fdev

Please keep coverage improvements PRs to at least **+0.5%**. Consider positive and negative tests

**Comment by jcchavezs** [comment]
I don't think we aim to 100% but I also think we heavily improved the coverage. Worth to keep this issue open? cc @fzipi
