### ISSUE TITLE
getting issue while trying to install

### ISSUE THREAD

**Issue by rajkumarks7** [corazawaf/coraza#466]
## Description
ubuntu : 22
go version: 1.18.1
Describe the issue that you're seeing.
getting the issue as wrong path. 
### Steps to reproduce
please do go get github.com/jptosso/coraza-waf/v2@latest
Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

### Expected result
coraza would have installed.
What should happen?

### Actual result

What happened.
go: github.com/jptosso/coraza-waf/v2@v2.0.1: parsing go.mod:
	module declares its path as: github.com/corazawaf/coraza/v2
	        but was required as: github.com/jptosso/coraza-waf/v2

**Comment by rajkumarks7** [comment]
@jptosso can you please look into this one ?

**Comment by rajkumarks7** [comment]
@anuraaga  thanks you it worked. for me 
 the below is the link i am following.
[https://coraza.io/docs/tutorials/quick-start/#add-coraza-to-your-go-project](url)

can you please let me know if you have any examples to block the outbound rules for a specific ipaddress.

**Comment by jcchavezs** [comment]
Ping @m4tteoP

**Comment by M4tteoP** [comment]
> can you please let me know if you have any examples to block the outbound rules for a specific ipaddress.

Hi @rajkumarks7, by blocking you mean basically whitelisting a specific IP address just for a specific phase?
If so, can something starting from the following one be helpful? Keep in mind that rules order matter.
```
SecRule REMOTE_ADDR "@contains 127.0.0.1" "id:111,phase:4,allow,ctl:ruleEngine=Off"
```

**Comment by jptosso** [comment]
Hey! Sorry for the late response. Please specify the version using the following:
```sh
go get -u github.com/corazawaf/coraza/v2@v2.0.1
```

**Comment by rajkumarks7** [comment]
@M4tteoP ok

**Comment by jcchavezs** [comment]
Can we close this @rajkumarks7 ?

**Comment by M4tteoP** [comment]
Closing as answered
