### ISSUE TITLE
I follow the documentation and get an error

### ISSUE THREAD

**Issue by pretty66** [corazawaf/coraza#469]
#### I followed the steps of [document](https://coraza.io/docs/tutorials/coreruleset/) to integrate the OWASP core ruleset, and an error occurred. The following is all my code and the error message after running
```go
package main

import (
	"fmt"
	"log"
	"net/http"

	"github.com/corazawaf/coraza/v3"
	txhttp "github.com/corazawaf/coraza/v3/http"
)

func hello(w http.ResponseWriter, req *http.Request) {
	fmt.Fprintf(w, "hello world, not disrupted.\n")
}

func main() {
	waf := createWAF()
	http.Handle("/hello", txhttp.WrapHandler(waf, nil, http.HandlerFunc(hello)))
	fmt.Println("Server is running. Listening port: 8090")
	log.Fatal(http.ListenAndServe(":8090", nil))
}

func createWAF() coraza.WAF {
	waf, err := coraza.NewWAF(
		coraza.NewWAFConfig().WithDirectivesFromFile("coraza.conf").
			WithDirectivesFromFile("coreruleset/crs-setup.conf.example").
			WithDirectivesFromFile("coreruleset/rules/*.conf"),
	)
	if err != nil {
		log.Fatal(err)
	}
	return waf
}
```

<img width="1481" alt="image" src="https://user-images.githubusercontent.com/21053373/196386404-dcfdf996-e196-4e17-ba37-81475301a409.png">

#### Can you provide a detailed usage example, thanks a lot

**Comment by anuraaga** [comment]
Hi @pretty66 - I believe the latest coreruleset can sometimes have issues with regex that aren't compatible with go. We are working on improving the situation by adding a CI check to make sure that doesn't happen in the future.

What happens if you use `v4.0.0-rc1`?

https://github.com/coreruleset/coreruleset/releases/tag/v4.0.0-rc1

**Comment by pretty66** [comment]
Thanks for your reply @anuraaga , the above code is already using the latest version v4.0.0-rc1.

Below is my entire code

<img width="1209" alt="image" src="https://user-images.githubusercontent.com/21053373/197141367-039fb3c6-5246-4d79-8b1f-84115259e82e.png">

**Comment by jptosso** [comment]
Hey! The problem was related to a CRS rule and it was fixed in the latest CRS tag. Could you try again with the latest version?
