### ISSUE TITLE
Add header control capabilities

### ISSUE THREAD

**Issue by jptosso** [corazawaf/coraza#477]
Modsecurity 2 provides the https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#SecServerSignature  directive, which allows the user to remove a request header.

- Most Coraza connectors use the `http.Header` type to handle headers.
- `http.Header` is an alias to `map[string][]string`
- It represents a header that can contain multiple values, for example:
```http
GET / HTTP/1.1
Cookie: cookie1=value1
Cookie: cookie2=value2
```

## how to implement this

To accept headers, we currently use `tx.AddRequestHeader(key, value)`:
```go
for key, values := request.Headers {
  for _, value := range values {
    tx.AddRequestHeader(key, value)
  }
}
```

Our new implementation should provide the same mechanism plus:
```go
tx.AddRequestHeaders(key, request.Headers)
```
By using AddRequestHeaders we could store the headers map pointer in the transaction so the actions could access and manipulate them. If the Coraza connector sends the same headers object to the server, then we can control it.

**Comment by jcchavezs** [comment]
As far as I understand from https://www.feistyduck.com/library/modsecurity-handbook-free/online/ch04-logging.html#N11370 `sanitiseArg`, `sanitiseRequestHeader` and `sanitiseResponseHeader, and `sanitiseMatched` aren't meant to mutate the request but to remove them for audit logging. If that is the case we can implement something that 

```go
type HeaderDeleter interface {
  Del(key string)
}
```

and do `tx.AddHeaderDeleters(hd)` to register the header deleters and then apply them on loggging although the current audit logger does not contain headers, see https://github.com/corazawaf/coraza/blob/v3/dev/internal/corazawaf/transaction.go#L791.

If the idea is to mutate the request before it gets to upstream we could have an interface:

```go
type HeaderSetter interface {
  Set(key, value string)
}
```
and do `tx.AddHeaderSetter(hs)` which can be consumed by connectors before sending the request upstream.

In any case I think we should not give full access to the header map as it is unsafe.

**Comment by jcchavezs** [comment]
Also, before jumping into the implementation could you point out the use case for this?

**Comment by jptosso** [comment]
One interesting use case would be to sign cookies and perform signature validation in coraza. We could also add CSRF tokens.

**Comment by jcchavezs** [comment]
So which one is it? Do we want to mutate the request? if so, we need another action name because the one described originally is used for something else.

**Comment by jptosso** [comment]
`SecServerSignature`. I was thinking of something like this:
```apache
SecSignatureKey "%{ENV.signature_secret}"
SecSignRequestCookie "username"
# or
SecRemoveResponseHeader "Server"
# or 
SecUpdateHeader "Server" "Coraza :3"
```

**Comment by fzipi** [comment]
Wait. What's the `SecServerSignature` have to do with this?

There was a `SecHash*` idea before, not sure if this applies here also. At least for signing.

I agree that if we are mutating the request, we should clone the read-only headers and use a different structure. Otherwise, it gets too messy.

Regarding updating and remove headers in a directive, wouldn't those be triggered by a `ctl` transient action instead of a directive? They will apply on the request to the backend, or on the response from it?
