### ISSUE TITLE
ResponseArgs not defined but used in JSON response processor

### ISSUE THREAD

**Issue by anuraaga** [corazawaf/coraza#480]
There is a variable `ResponseArgs` but doesn't seem to be any corresponding collection.

https://github.com/corazawaf/coraza/search?q=responseargs

But it is referenced in the JSON body processor and presumably isn't causing a nil exception because the test cases don't deal with JSON responses (?). What should be the correct behavior?

**Comment by jptosso** [comment]
We should create the variable so it can be consumed by the body processor.

We also have to replicate the request body behavior into the responses, like adding forceResponseBody, setResponseBodyPRocessor, and set response body acceptable mimes

**Comment by fzipi** [comment]
Is this needed for v3?

**Comment by jptosso** [comment]
We should make sure this works as it is a breaking change.
We could temporarily move all plug-in interfaces into internal so we can test them and release them later.

**Comment by jcchavezs** [comment]
Is this the same issue as https://github.com/corazawaf/coraza/issues/595?

**Comment by jptosso** [comment]
Yes, the other issue details the implementation process, we can move the discussion here

**Comment by jcchavezs** [comment]
From @jptosso in #595

> This issue describes how to implement the RESPONSE_ARGS variables
>
> There are two specific use cases:
> - JSON
> - GraphQL
>
> For JSON we will just copy the behavior from the request body processor by collapsing the json into a map, like:
> ```
> {
>  "foo": "bar",
>  "bar": [1, 2]
>}
>```
>into:
> ```go
> m map[string][]string = {
>  "json.foo": {"bar"},
>  "json.bar.0": {"1"},
>  "json.bar.1:: {"2"},
>}
>```
>Some specific requirements for this implementation:
> - Are we setting the response body processor by using ctl:setResponseBodyProcessor?
> - Should we add additional directives to handle the maximum buffer sizes?
> - If there is no response body processor what happens?
> - Should we default to json when the response mime is json?
