### ISSUE TITLE
Implement WAF merge API

### ISSUE THREAD

**Issue by jptosso** [corazawaf/coraza#500]
Apache and nginx logic provides a hierarchy for the rule compilation, for example:

Virtual Host / Server (sample.com) -> Compile 3 Coraza Rules
--> Location inside Server (/test1) -> Compile 2 Coraza Rules
--> Location inside Server (/test2) -> Compile 1 Coraza rule

The result should be three instances of coraza WAF, sample.com contains 3 rules, /test1 contains a clone of sample.com plus the additional directives, /test2 contains a clone of sample.com plus the additional directive.

The copy should be a deep clone, we should not leave pointers connected to the original WAF.

Could we recycle the WAFConfig object? Should we store a list of directives? or should we clone everything manually? If we want to recycle WAFConfig we would have to provide something like `waf.Config()` to retrieve the original config, then we can add our new directives and create a new waf instance with the previous config.

**Comment by jcchavezs** [comment]
In this kind of case I would always follow the [brave immutability pattern](https://github.com/openzipkin/brave/blob/master/brave/src/main/java/brave/propagation/TraceContext.java#L211) where we can go from `builder -> object -> builder` (cc @codefromthecrypt).

In this specific case we could add a method `WAF.ToConfig` which would return a copy of the waf config that can be reused to create a new WAF that inherits rules from the parent.

cc @anuraaga

**Comment by codefromthecrypt** [comment]
builders are polarizing discussions, I will bow out ;)

**Comment by anuraaga** [comment]
`WAFConfig` is already immutable, @jptosso do you get the merge semantics with just something like?

```
conf := coraza.NewWAFConfig()

sampleComConf = sampleComConfiguration(conf)
sampleComWaf := coraza.NewWAF(sampleComConf)

test1Conf = test1Configuration(sampleComConf)
test1Waf := coraza.NewWAF(test1Conf)

test2Conf = test2Configuration(sampleComConf)
test2Waf := coraza.NewWAF(test2Conf)
```

**Comment by jptosso** [comment]
@anuraaga in this use-case, there are three implementations using the same sample configuration, we need deep copies of the configurations, as the second configuration will append directives that we don't want for the third configuration. Can we use the current implemenation to achieve this? It should look something like:

```go
sampleConfig := coraza.NewWAFConfig()
sampleWaf := coraza.NewWAF(sampleConfig)
// ...
sampleConfig2 := sampleWaf.ToConfig()
sampleWaf2 := coraza.NewWAF(sampleConfig2)
```

**Comment by anuraaga** [comment]
@jptosso Oops that's a bug - send #501

**Comment by fzipi** [comment]
What is needed here now? Did #501 fix this?

**Comment by fzipi** [comment]
Sadly this wasn't fixed yet.

**Comment by jcchavezs** [comment]
Are we still doing this?

**Comment by fzipi** [comment]
Why not? It doesn't need to be solved now. But this is a prereq for nginx/apache, so let's keep it open and see if the community wants it.
