### ISSUE TITLE
Missing "hostname" key in logs

### ISSUE THREAD

**Issue by mac-chaffee** [corazawaf/coraza#515]
## Description

As discovered here: https://github.com/jcmoraisjr/haproxy-ingress/pull/964#issuecomment-1322546679

Logs appear to be missing the hostname key (newlines inserted for visibility):

```
Loading 1 applications
time="2022-11-21T19:21:07Z" level=info msg="spoe: listening on [::]:9000"
{"level":"error","ts":1669058760.188159,"msg":"[client \"10.100.0.172\"] Coraza: Warning. OS File Access Attempt 
[file \"/etc/coraza-spoa/rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf\"] [line \"0\"] [id \"930120\"] [rev \"\"] 
[msg \"OS File Access Attempt\"] [data \"Matched Data: etc/passwd found within ARGS:p: /etc/passwd\"] [severity \"critical\"] 
[ver \"OWASP_CRS/4.0.0-rc1\"] [maturity \"0\"] [accuracy \"0\"] [tag \"application-multi\"] [tag \"language-multi\"] 
[tag \"platform-multi\"] [tag \"attack-lfi\"] [tag \"paranoia-level/1\"] [tag \"OWASP_CRS\"] [tag \"capec/1000/255/153/126\"] 
[tag \"PCI/6.5.4\"] 
[hostname \"\"]   <---
[uri \"/?p=/etc/passwd\"] [unique_id \"260e3d15-dd04-41b7-a634-45d17f0a8390\"]\n"}
```

If I'm reading the code correctly, that log value is always set to an empty string: https://github.com/corazawaf/coraza/blob/9d003ed52753367b75383566ca69bc3d467cc8a0/internal/corazarules/rule_match.go#L123-L139

When multiple sites are fronted by a single server running Coraza, you need the hostname field to tell which site triggered the rule.

Since Coraza scans the headers anyway, it might be possible to just grab the `Host` header to populate that `hostname` field. HTTP says that header is required anyway.

**Comment by fuomag9** [comment]
Related issue https://github.com/corazawaf/coraza-caddy/issues/35

**Comment by M4tteoP** [comment]
Current situation and Coraza/Modsec comparison:
-----------
**ModSec v3**:
- Populates `m_variableServerName` looking for the host header (see [here](https://github.com/SpiderLabs/ModSecurity/blob/12e6e325d1e6367f61dbaecc314919b99eed67fa/src/transaction.cc#L702-L705)).
- Logs side: the hostname field is populated with the server IP (see [here](https://github.com/SpiderLabs/ModSecurity/blob/12e6e325d1e6367f61dbaecc314919b99eed67fa/src/rule_message.cc#L45)).

**Currently Coraza**:
- `tx.variables.serverName` is never populated, therefore `SERVER_NAME` is always empty.
- Logs: the `hostname` field is empty.

Possible Fixes
-----------
**SERVER_NAME**:
1. Populate it with host header Coraza side (just like ModSec)
2. Just like other connection details (IP, ports), let's delegate its retrievement to the connectors adding one field to `ProcessConnection`. If empty string, let's populate it with the IP address. (Accoring to ModSec doc: `SERVER_NAME: contains hostname or IP address`.

**Logs**:
- [Current PR](https://github.com/corazawaf/coraza/pull/517) adds the server IP to the `hostname` field for logging.
- Once `tx.variables.serverName` is populated we may sanitize (at least check allowed characters?) and two different fields for address and hostname.

I'm happy to work on it, I just want to agree on the implementation. At first sight, I would go for adding one field to `ProcessConnection`, could some connectors be aware of the hostname there are listening at and not have to look at the headers?

**Comment by jcchavezs** [comment]
@fuomag9 @mac-chaffee we just medged the fixing PR. Could you please test it?

**Comment by M4tteoP** [comment]
The merged PR aligns the `hostname` field for logging to the ModSec behaviour, still, I think that it is a partial fix mainly because of the never populated `SERVER_NAME` field. I'm gonna open a PR that proposed to delegate it to `ProcessConnection` (Option `2` of my above comment).
