### ISSUE TITLE
unset CRS variables while calling ProcessLogging with RuleEngine Off

### ISSUE THREAD

**Issue by M4tteoP** [corazawaf/coraza#520]
## Description

Hello! I'm [experiencing](https://github.com/corazawaf/coraza-proxy-wasm/pull/101#discussion_r1033559076) some errors while running the CRS with the RuleEngine Off.
Error example:
```
  Invalid value for setvar "+tx.blocking_outbound_anomaly_score" on rule 980099
```
It happens because CRS at phase 5 looks at variables set at phase 1, but with the engine off, that initialization may not happen.
Any thoughts? 
I'm reading a consideration about ModSec not logging if the engine is off: 
https://github.com/corazawaf/coraza/blob/63a49c8b17230f81a1a812298cbc0c336e59b15f/internal/corazawaf/transaction.go#L905-L908
What do we expect to log in that case? It seems to be the only place where we call `tx.WAF.Rules.Eval` even if the engine is off 🤔

Thanks!

**Comment by fzipi** [comment]
From what I see in the ModSecurity code, none of the processing is made when the engine is off.
And in particular, in the logging phase:
```
int Transaction::processLogging() {
    ms_dbg(4, "Starting phase LOGGING. (SecRules 5)");

    if (getRuleEngineState() == RulesSet::DisabledRuleEngine) {
        ms_dbg(4, "Rule engine disabled, returning...");
        return true;
    }
...
```
So I would say we activate that code.
