### ISSUE TITLE
Enhance support for XML Request Body processor

### ISSUE THREAD

**Issue by fzipi** [corazawaf/coraza#522]
## Summary

The XML Request Body processor only supports basic features, because of the lack of proper support for XPath libraries in Go. 

### Basic example

https://github.com/corazawaf/coraza/blob/v3/dev/bodyprocessors/xml.go#L35-L59

This is mentioned in our own configuration, but I don't know why the support isn't there: https://github.com/antchfx/xpath

### Motivation

Having the full XPath will allow users to have a full request body processor.

**Comment by jcchavezs** [comment]
Shall we label this as a nice to have? I would like to see users requesting
for full XML support so we can see in the use cases to what degree we
should support.
