### ISSUE TITLE
User Agent parser (IDEA)

### ISSUE THREAD

**Issue by jptosso** [corazawaf/coraza#530]
Maybe we could add a new variable to get information about the user-agent, something like:
```json
"USER_AGENT": {
  "vendor": "Google",
  "version": "...",
  "javascript_engine": "",
  "is_browser": true,
  "features": [...]
}
```

We could perform validations like:
```
SecRule USER_AGENT:is_browser "@eq 1" "...msg:'user is user a web browser'"
```

**Comment by jcchavezs** [comment]
Could you describe the use case? Also, what would be the source of truth to
detect the user agent and determining the vendor,  js_engine and if it is
browser or not and how are we maintaining that list. Is this somehow
described in CRS? Cc @fzipri
