### ISSUE TITLE
Should removeWhitespace work on unicode?

### ISSUE THREAD

**Issue by anuraaga** [corazawaf/coraza#550]
Currently, removeWhitespace operates on unicode characters / spaces. ModSecurity is only latin I think

https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/actions/transformations/remove_whitespace.cc#L49

compressWhitespace is currently operating on latin (also after #544). This matches ModSecurity behavior

https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/actions/transformations/compress_whitespace.cc#L46

Should removeWhitespace be changed to work on latin for consistency with compressWhitespace and ModSecurity?

**Comment by jcchavezs** [comment]
Pinging @fzipi, @airween and @jptosso as they might have good feedback on this.
