### ISSUE TITLE
Expose ErrorLogCallback

### ISSUE THREAD

**Issue by sts** [corazawaf/coraza#555]
`coraza.ErrorLogCallback` was moved to internal package, but it's used in a public interface. Please expose it again.

**Comment by jcchavezs** [comment]
Up for a PR?

**Comment by anuraaga** [comment]
Interestingly we set an error callback outside this repo here

https://github.com/corazawaf/coraza-proxy-wasm/blob/main/wasmplugin/plugin.go#L61

I guess Go duck typing works ok in this case. Still public API shouldn't refer to an internal type so good to fix but just curious if you're blocked

**Comment by sts** [comment]
Its not blocking at the moment. https://github.com/corazawaf/coraza-spoa/blob/upgrades_coraza/internal/spoa.go#L40
