### ISSUE TITLE
InboundErrorData vs InboundDataError

### ISSUE THREAD

**Issue by anuraaga** [corazawaf/coraza#564]
Currently we have both InboundErrorData and InboundDataError. InboundDataError isn't set automatically, and InboundErrorData is set when the request body is too large. However, OutboundDataError (not OutboundErrorData) is set when the response body is too large. This ordering of the words isn't consistent for the two - is it correct?

**Comment by jcchavezs** [comment]
Ping @jptosso @fzipri
