### ISSUE TITLE
Monthly meeting agenda (January 2023)

### ISSUE THREAD

**Issue by jptosso** [corazawaf/coraza#582]
- **Date:** [_Wednesday, January 25 at 12 p.m. UTC_](https://dateful.com/convert/utc?t=12pm&d=2023-01-25)
- **Previous agenda:** https://github.com/corazawaf/coraza/issues/474

### Current agenda
1. General project status
2. Pending for v3 release
3. https://github.com/corazawaf/coraza/discussions/581
4. https://github.com/corazawaf/coraza/pull/512
5. https://github.com/corazawaf/coraza/pull/572
6. [OWASP Global AppSec Dublin](https://owasp2023globalappsecdublin.sched.com/event/439bf2286bf4661570e267b812ed41cc)
7. https://github.com/corazawaf/coraza/issues/583
8. 👉 We have to update documentation... 👈 
9. https://github.com/corazawaf/coraza/pull/519

### How to join?
1. Join OWASP slack: https://owasp.org/slack/invite
2. Join the #coraza channel: https://owasp.slack.com/archives/C02BXH135AT

### Calendar Event
[Download calendar event (ICS)](https://calendar.google.com/calendar/ical/c_s1vf6auene1ehionfslv010tk8%40group.calendar.google.com/public/basic.ics)

**Comment by liweijian** [comment]
Cool, the link behind the `Date` would be `https://dateful.com/convert/utc?t=12pm&d=2023-01-25`
