### ISSUE TITLE
Implement RESPONSE_ARGS

### ISSUE THREAD

**Issue by jptosso** [corazawaf/coraza#595]
This issue describes how to implement the RESPONSE_ARGS variables

There are two specific use cases:
- JSON
- GraphQL

For JSON we will just copy the behavior from the request body processor by collapsing the json into a map, like:
```json
{
  "foo": "bar",
  "bar": [1, 2]
}
```
into:
```go
m map[string][]string = {
  "json.foo": {"bar"},
  "json.bar.0": {"1"},
  "json.bar.1:: {"2"},
}
```

Some specific requirements for this implementation:
- Are we setting the response body processor by using ctl:setResponseBodyProcessor?
- Should we add additional directives to handle the maximum buffer sizes?
- If there is no response body processor what happens?
- Should we default to json when the response mime is json?

**Comment by jcchavezs** [comment]
Let's continue the discussion in https://github.com/corazawaf/coraza/issues/480
