### ISSUE TITLE
Parser lowercases user-passed string literal in rule

### ISSUE THREAD

**Issue by anuraaga** [corazawaf/coraza#599]
Currently, any variable key is lowercased

https://github.com/corazawaf/coraza/blob/v3/dev/internal/corazawaf/rule.go#L392

This seems odd to me since keys are user configuration and should be correct based on what the user wants. However, if this is something to preserve compatibility with ModSecurity then it is what it is, would like to confirm it.

We are currently in a strange situation though

- Variables added by `AddArgument` can be fetched by key since it is a case-insensitive match (#598)
- Variable keys (not values) added by `AddArgument` cannot be matched by regex - the key is stored lowercase and regex matched against that
- Variables added by body processors cannot be fetched by key since they are stored as-is, but fetch key is always lowercase
- Variable keys (not values) added by body processors can be matched by regex - the key is stored as-is and regex matched against that

FTW seems to somehow only test situations that do not fall into the above gaps, or perhaps its one of our FTW failures (@M4tteoP?). 

We need to decide the behavior for all of this. I think ideally arguments should be added case-sensitive and rule keys should have case preserved, but may not know about some compatibility reason to avoid this.

@jptosso @fzipi @M4tteoP @jcchavezs

**Comment by anuraaga** [comment]
Also note the tests related to case around here

https://github.com/corazawaf/coraza/blob/v3/dev/internal/seclang/rules_test.go#L744

This test is saying that `TESt1` should only match once for `test1`, `Test1`, `TEST1`, but seemingly should be zero matches and the rule can use a lowercase transform or case insensitive regex, etc to be made generic.

**Comment by anuraaga** [comment]
@piyushroshan I heard you may be interested in this

**Comment by piyushroshan** [comment]
The behavior taken by ModSecurity is the keys for args are case insensitive in variable key references like ARGS:Test is same as ARGS:test hence keys are in lowercase. However the names/keys collection store the variable in their case. The body processors too should add the keys in lowercase for ARGS collection and in the specific case for ARGS_NAMES.

**Comment by piyushroshan** [comment]
IMO it was done because headers names/cookie names specific variable reference needs to be done in a case-insensitive manner regardless of input preventing bypasses. 
Hence when referencing specific headers it needed to ignore the case as it is not known what case the header may come in.

**Comment by anuraaga** [comment]
Thanks @piyushroshan - I also found https://github.com/SpiderLabs/ModSecurity/commit/910a1877a9ec673f36c139e6a3e941812b8e986e which currently in Coraza is still actually case-sensitive matching for regex I think. Will look at fixing this all up.

**Comment by jcchavezs** [comment]
Is this still an issue?
