### ISSUE TITLE
Create geoip plugin

### ISSUE THREAD

**Issue by fzipi** [corazawaf/coraza#611]
## Summary

We are discussing official plugins from the Coraza community. Geoip has been flagged as an official plugin, so we should provide official support for it.

There was a discussion on this topic in: https://github.com/corazawaf/coraza/discussions/581

### Basic example

TBF.

### Motivation

TBF.

**Comment by jptosso** [comment]
We should provide a file plug-in for two vendors, ip2location and maxmind

We should also discuss how wasm is going to handle this without fs access

**Comment by daum3ns** [comment]
hello!
i am a little bit confused about whats  the state of geoIP support in coraza. (specifically in the coraza-proxy-wasm loaded in envoy). How is this related to this repository https://github.com/corazawaf/coraza-geoip
