### ISSUE TITLE
Cannot diable two rules on different URIs

### ISSUE THREAD

**Issue by undergroundwires** [corazawaf/coraza#617]
I use latest [coraza-caddy](https://github.com/corazawaf/coraza-caddy) with Caddy along with core ruleset.

My Caddyfile configuration looks like:

```caddyfile
coraza_waf {
	include /waf/extra-rules.conf # Must be imported before other rules for exceptions to work.

	# As recommended by https://github.com/corazawaf/coraza-caddy
	include /waf/coraza.conf-recommended
	include /waf/coreruleset/crs-setup.conf.example
	include /waf/coreruleset/rules/*.conf
	}
```

In `/waf/extra-rules.conf` I have some URI-based exceptions which work fine. However, if I disable same rule on two different URI based rules, the whole file is ignored and none of the exceptions work.

So this works fine:

```modsecurity
SecRule REQUEST_URI "@beginsWith /test1" \
      "id:1000101,\
      phase:1,\
      pass,\
      nolog,\
       ctl:ruleRemoveById=911100"
```

But If I add one more rule that will run `ruleRemoveById` on different URI (e.g. `/test2`), all other exceptions in the file fails and are ignored. This configuration does not work:

```modsecurity
SecRule REQUEST_URI "@beginsWith /test1" \
      "id:1000101,\
      phase:1,\
      pass,\
      nolog,\
       ctl:ruleRemoveById=911100"

SecRule REQUEST_URI "@beginsWith /test2" \
      "id:1000201,\
      phase:1,\
      pass,\
      nolog,\
       ctl:ruleRemoveById=911100"
```

**Comment by undergroundwires** [comment]
Thank you for quick action @jcchavezs , happy to see this repo being maintained nicely. This time it was my misconfiguration, no problem from coraza side. Please ignore this issue completely. Thank you all four your efforts for coraza.

**Comment by jcchavezs** [comment]
Awesome, thanks!
