### ISSUE TITLE
Expose AuditLog export API

### ISSUE THREAD

**Issue by jptosso** [corazawaf/coraza#648]
There might be use-cases where we need to programmatically extract the audit log directly from the transaction, just like the error string. Transaction's public interface should export something like `AuditLog()`

It will also provide audit log for the playground

**Comment by jcchavezs** [comment]
Could you please list some of the *might be use-cases* to do the tradeoffs
about this case?

**Comment by jcchavezs** [comment]
For example, for the playground issue we can easily plug a writer in the audit log which can be read later.
