### ISSUE TITLE
Validate audit log parts

### ISSUE THREAD

**Issue by jcchavezs** [corazawaf/coraza#678]
## Summary

Right now we don't validate audit log parts, instead we just accept what is coming. Types package should not only declare them but also validate them.

For example in https://github.com/corazawaf/coraza/blob/c68f247ffac02b2706053643b80453de7d01de31/internal/seclang/directives.go#L753 and https://github.com/corazawaf/coraza/blob/c41dbfc3563e19e12d2c61bf1335c034a6870069/actions/ctl.go#L114-L115 do the casting directly without validating the actual values.

**Comment by Violet-E** [comment]
if the Opts contains invalid AuditLogPart,if AuditLogParts should be null and return error or just remove the invalid AuditLogPart

**Comment by jcchavezs** [comment]
It should return an error to fail the parsing.

**Comment by jcchavezs** [comment]
After looking at docs (and actually the code too) part `A` is always required (see https://coraza.io/docs/seclang/directives/#secauditlogparts). Do you mind taking a stab @Hayak3 ?

**Comment by Hayak3** [comment]
> After looking at docs (and actually the code too) part `A` is always required (see https://coraza.io/docs/seclang/directives/#secauditlogparts). Do you mind taking a stab @Hayak3 ?

I will read the doc and fix it soon

**Comment by Hayak3** [comment]
I also find end with `Z` is mandatory,is it necessary? @jcchavezs

**Comment by jcchavezs** [comment]
Totally and we should also condition this assignment only when `Z` is
reached
https://github.com/corazawaf/coraza/blob/v3/dev/internal/corazawaf/transaction.go#L1414.
Could you please also take care of that?
