### ISSUE TITLE
Remove hack to prevent GET variables from overriding POST in json processor

### ISSUE THREAD

**Issue by anuraaga** [corazawaf/coraza#696]
In JSON processor, we have this code to remove keys found in a JSON payload from query parameters

https://github.com/corazawaf/coraza/blob/v3/dev/bodyprocessors/json.go#L28

How query parameters and JSON payload get merged is completely app-specific, so removing variables from query from processing seems dangerous, e.g. especially without multiphase evaluation, a log4shell trigger in query parameter seems like it would be allowed if it's together with a JSON payload.

Should we just remove this logic and let the value be present in both locations?

**Comment by dune73** [comment]
Very hard to gauge for me. It can be a useful feature. But it can also kill a service.

If you do not want to risk, then remove it.

Personally, I would remove it or make it opt-in. Definitely not `on` by default.

**Comment by jcchavezs** [comment]
Thanks Christian. Shall we remove it then?

**Comment by jptosso** [comment]
I wrote that code to avoid the following attack:

```http
POST /test.php?json.data.0=foo
....
Content-Type: application/json

{
  "data": ["var"]
}
```

**Comment by anuraaga** [comment]
Can you describe the attack? As far as I know, ARGS or similar composite vars should see both entries and have rules applied.

**Comment by jptosso** [comment]
I'm ok with removing this, it was a bad assumption
