### ISSUE TITLE
Confirm actions parse skipping whitespace

### ISSUE THREAD

**Issue by anuraaga** [corazawaf/coraza#702]
I was looking at actions parsing code and saw this sort of whitespace skipping

https://github.com/corazawaf/coraza/blob/v3/dev/internal/seclang/rule_parser.go#L428

This makes it seem like the following action strings are equivalent, is it supposed to be? 

`ph as e:1,msg:he llow or ld`
`phase:1,msg:helloworld`

Skipping whitespace within a key seems particularly weird, also compressing unquoted whitespace in a value seems surprising to me too.

**Comment by dune73** [comment]
This is very much an engine problem. I do not have a qualified opinion on pros and cons here.
