### ISSUE TITLE
`ErrorLog` code parameter always used with a hardcoded integer

### ISSUE THREAD

**Issue by M4tteoP** [corazawaf/coraza#795]
ErrorLog is exposed inside the MatchedRule interface as `ErrorLog(code int) string`. The `code` parameter should be used for logging the status code enforced by the disruptive action even if I think that the code that prints `Coraza: Access denied with code %d` is not working (Fix is https://github.com/corazawaf/coraza/pull/792/commits/c105d115d595682a3dc90090b2abaeae3e5ec670 that is part of https://github.com/corazawaf/coraza/pull/792). I'm mainly wondering how we are using the exposed `ErrorLog(code int)` because we are always calling it with a hardcoded integer.
-  [Coraza-proxy-wasm](https://github.com/corazawaf/coraza-proxy-wasm/blob/30eeff0ab77f65a6e422ffbbe4bf7ffa2643436a/wasmplugin/plugin.go#L654) and the [HTTP-server go example](https://github.com/corazawaf/coraza/blob/27b14f8cb47b27d1d70200cc0264810412a1ad18/examples/http-server/main.go#L60) call it as `ErrorLog(0)`.
- [Coraza-caddy](https://github.com/corazawaf/coraza-caddy/blob/94eb7b01a0fca1d025d3601c2ec227d79c43fc64/coraza.go#L198) as `mr.ErrorLog(403)`.

I feel that using it that way is not meaningful, we are not printing the real status code enforced by the connector, not the one that the Coraza framework writes inside the interruption.

Should we propagate the status code expected by the triggered rule via `MatchedRule` (e.g. just like we are doing with `mr.Disruptive_`) and remove the parameter from the callback, or currently the connectors are implementing the callback in the wrong way?

Thanks!

cc. @jptosso

**Comment by jptosso** [comment]
But what if we are on detectOnly and corasza status is 403 but the app's status is 200?

**Comment by M4tteoP** [comment]
That specific case should be taken care by the logic that fixes the `mr.Disruptive_` propagation just merged with https://github.com/corazawaf/coraza/pull/792: https://github.com/corazawaf/coraza/blob/v3/dev/internal/corazawaf/transaction.go#L489-L497. Basically the matched rule is marked as Disruptive only if the engine is on, not only if we have a disruptive action.

Generally speaking, I agree, the status in the end is enforced by the connector, we should propagate it from there, but it is something that I think we are not doing considering that we are just hardcoding status codes 🤔

**Comment by jcchavezs** [comment]
Can we have this explicit with a test?

**Comment by anuraaga** [comment]
Since we provide the transaction id to the connector, maybe it's just the job of the connector to log status in its normal http access log way with that ID included rather than trying to pass back to waf, which we've found to be challenging. Especially in a proxy, the real status code may end up being changed by a different filter anyways causing a mismatch between waf and http log.

**Comment by jcchavezs** [comment]
So as far as I understand even if we pass the right one, is still meaningless as exposed by @anuraaga. Shall we remove it then? cc @M4tteoP

**Comment by M4tteoP** [comment]
Removing it would be a change like this: https://github.com/corazawaf/coraza/pull/800
