### ISSUE TITLE
Implement Redis support as Collection backend

### ISSUE THREAD

**Issue by amsnek** [corazawaf/coraza#830]
## Summary
Modsecurity once intended to allow direct audit log writting to different backends (via network). Redis would be an interesting choice for shipping logs directly, skipping the need for local file based writes. This feature was never implemented in Modsecurity, discussed here: https://github.com/SpiderLabs/ModSecurity/issues/1139

### Basic example
```
SecAuditLogFormat JSON
SecAuditLogType REDIS
SecAuditLog redis://user:pass@redis.tld:6379/1
SecAuditLog redis://:token@redis.tld:6379/1?ssl_cert_reqs=CERT_REQUIRED
```

### Motivation

Writing directly to an collection backend would remove the need for local file storage, possibly increase security (log tampering) but also add additional challenges (retransmit? caching of logs in case of collection failure etc). This subject may need further discussion, but overall it would be a significant Feature.

**Comment by jptosso** [comment]
Hey! Collection backends are not for audit logs, but for persistence. And persistence is not supported by Coraza yet :( 
Also, this is something we have studied and there are other massive problems, like a strong delay for each transaction. It would only work on an environment that requires an asynchronous waf.

Regard,

**Comment by jcchavezs** [comment]
I think this could work same as http does but also thing this should be a
plugin. I think redis would be just another option to send logs to (same as
writing a file) we just need to make sure all the overhead of persisting to
an external don't get added to the critical path (e.g. using goroutines,
batching or anything else). Are you @amsnek up to start some work in your
own repository? You can get inspired by
https://github.com/corazawaf/coraza/blob/main/experimental/plugins/auditlog_writer_test.go.
That said I don't see this landing in coraza repo unless we find out this
is the defacto behaviour.

**Comment by jcchavezs** [comment]
Any feedback on this @amsnek ?

**Comment by amsnek** [comment]
Oh, sorry! I somehow did not receive Notifications for the responses here. 
This feature request was more of a suggestion/idea and mostly born out of issues I encountered with modsecuritys concurrent/serial file based logging. (and Audit Logs without a central collection backend are mostly useless). 
Since I would very much like to switch to coraza in the medium Future, I was mostly thinking head and also hoping to avoid issues already encountered in the past. 
I am not a developer however, and lack the knowledge/skillset to implement these features :( These was mostly brainstorming and to probe if I missed something were there may be already a (better) solution. 
This was also born out of my question (http endpoint) here: https://github.com/corazawaf/coraza/discussions/813

Currently I use modsecurity with SecAuditLogType HTTPS since other apporaches are not practical depending on the amount of logs, partially to the way filebeat works (rotation etc). 

Shall I close this Request?

**Comment by jcchavezs** [comment]
Thanks for the explanation @amsnek, it is totally fine and helpful to get this kind of issues because it serves for context to the next person needing this feature. Let's close it because there won't be immediate action here and feel free to repoen it once this becomes a blocker to deploy coraza.
