### ISSUE TITLE
Implement multiple regex backends

### ISSUE THREAD

**Issue by jptosso** [corazawaf/coraza#843]
Right now, we are facing multiple issues because of going re2 performance. Let's enable multiple backends and provide build tags to select which one to use. There have been multiple discussions around this, and I'm aware of multiple vendors replacing go re2 with another backend. See https://github.com/corazawaf/coraza/discussions/842

Backends I suggest:
- Go (The slow one)
- [Wasilibs go-re2](https://github.com/wasilibs/go-re2)
- [Hyperscan](https://github.com/intel/hyperscan)
- Maybe PCRE2? It would be an irony after working so hard to migrate CRS 😖 

Compile tag could be something like
- --rx-backend-re2
- --rx-backend-go (default)
- --rx-backend-hyperscan

Let's try to involve Intel in this.

### Minimum requirements for this implementation
- Deploy all tests for multiple backends, re2, go, and hyperscan
- Update the documentation with instructions and benchmarks for each backend
- Consider limitations in backends like single character matches and the hacks we are using right now using binary regexp

**Comment by jcchavezs** [comment]
I would not support different implementations but instead allow people to
chose the implementation while we support a default one. If we go re2 we
support it and no need to support go regex because it will create burden in
maintenance.

**Comment by jptosso** [comment]
I agree. Should we go for plug-ins ?

**Comment by anuraaga** [comment]
We already sort of have plugins in experimental API. Enabling is just one line of code

https://github.com/corazawaf/coraza-wasilibs

I don't know if it's worth having a build tag as well on top of it.
