### ISSUE TITLE
Coraza WAF SecResponseBodyLimit Bug: Incomplete Response Handling

### ISSUE THREAD

**Issue by peasfarmer** [corazawaf/coraza#891]
## Description

I'm encountering an issue with the Coraza WAF. When I set the `SecResponseBodyLimit` to 100K and also set `SecResponseBodyLimitAction` to `ProcessPartial`, I expected the WAF to check only the first 100K of the response and send the complete body to the client when the response is large. However, I observed that Coraza WAF is only sending 100K to the client and not delivering the exceeding portion.
Similarly, I've also encountered a problem with the SecRequestBodyLimitAction parameter.

### Steps to reproduce

1. Configure Coraza WAF with `SecResponseBodyLimit` set to 100K and `SecResponseBodyLimitAction` set to `ProcessPartial`.
2. Trigger a request that generates a response larger than 100K.

### Expected result

The expected behavior is that Coraza WAF should process only the first 100K of the response content but still deliver the complete body to the client when the response is larger.

### Actual result

The actual result is that Coraza WAF restricts the response to 100K and does not provide the exceeding portion to the client.

**Comment by jcchavezs** [comment]
Hi @peasfarmer thanks for coming by. I wonder what connector of coraza are you using, if it is the [http one](https://github.com/corazawaf/coraza/tree/main/http) we do check that the response body is the expected one in this test https://github.com/corazawaf/coraza/blob/main/http/middleware_test.go#L467.

**Comment by jcchavezs** [comment]
Thank you!
