### ISSUE TITLE
/tmp "crzmp*" never deleted after a POST

### ISSUE THREAD

**Issue by UnveilTech** [corazawaf/coraza#922]
Hi,
file: /corazawaf/coraza/v3@v3.0.1/internal/bodyprocessors/multipart.go
line: 61

"/tmp/crzmp*" files are never deleted after a POST.

bye Fred

**Comment by jcchavezs** [comment]
Totally. Do you mind coming up with a PR fixing it?

**Comment by UnveilTech** [comment]
Hi,
my issue is to inform the team, then it should be nice to fix it...

**Comment by UnveilTech** [comment]
thnaks :o)

**Comment by victoredvardsson** [comment]
@jcchavezs @jptosso What is the status of this one? Currently our servers are running out of space since these are never deleted.

**Comment by victoredvardsson** [comment]
Hm ok, im using https://docs.crowdsec.net/docs/next/appsec/intro which should be using Coraza as engine for processing SecLang rules. Maybe its a bug at their end.

**Comment by M4tteoP** [comment]
> This was fixed long time ago in https://github.com/corazawaf/coraza/pull/924

I might have missed something, but #924 is open so we probably have not yet a fix merged. 

> On another note, do you know if these files are also created by coraza "body999644643"?

I think you are referring to these files, created when the in-memory buffered is full: https://github.com/corazawaf/coraza/blob/ec0497a6da32f63572ff4b89fbf10beb28ab89c4/internal/corazawaf/body_buffer.go#L78

**Comment by M4tteoP** [comment]
> So what is the actual difference between crzmp* and body*?

crzmp* stores files that are getting uploaded as `multipart/form-data`, while `body*` stores generic POST body payloads that are bigger than the in-memory limit

**Comment by victoredvardsson** [comment]
> > So what is the actual difference between crzmp* and body*?
> 
> 
> 
> `crzmp*` stores files that are getting uploaded as `multipart/form-data`, while `body*` stores generic POST payloads that are bigger than the in-memory limit

Thanks a lot for explaining. I guess the only option for now is to schedule some cron that actively deletes these files twice a day or so.
