### ISSUE TITLE
Raw body processor

### ISSUE THREAD

**Issue by blotus** [corazawaf/coraza#938]
Currently, coraza implements 4 body processors:
 - `urlencoded`: for urlencoded body
 - `multipart`: for multipart body
 - `json`: for JSON body
 - `xml`: for XML body

The choice is the body processor is often (always ?) based on the `Content-Type` header, and coraza defaults to `urlencoded` if no body processor has been set (eg if the request has an unknown content type) and `ForceRequestBodyVariable` is set, meaning that parsing a body of unknown type might waste some time by trying to parse it as urlencoded for nothing (and possibly set some "garbage" variables if you happen to have a `&` in it)

It would be nice to have a `raw` body processor that does nothing but set both `REQUEST_BODY` and `REQUEST_BODY_LENGTH` (maybe not as a default, as it would probably be a huge breaking change, but at least offer the possibility for the user to use it)

**Comment by jptosso** [comment]
Thank you for your proposal
What is your use case?

**Comment by jcchavezs** [comment]
QQ: can't you set a custom body processor?

**Comment by blotus** [comment]
> Thank you for your proposal What is your use case?

Sorry, maybe it was not clear enough in my initial issue, for me it's more of a "correctness"  thing: if you receive a request with either no content type or a content type that is not handled in your configuration, trying to parse the body as urlencoded might lead to some garbage data in the variables.

> QQ: can't you set a custom body processor?

This is what I did (you can see it [here](https://github.com/crowdsecurity/crowdsec/blob/master/pkg/acquisition/modules/appsec/bodyprocessors/raw.go)), but I thought it would be interesting to have this out of the box.

**Comment by jcchavezs** [comment]
Sounds reasonable to me cc @Anuraag Agrawal ***@***.***>

**Comment by jcchavezs** [comment]
Just a final question: if you don't want the body to be processed why do
you want the REQUEST_BODY and REQUEST_BODY_LENGTH variables to be set?

**Comment by blotus** [comment]
> Just a final question: if you don't want the body to be processed why do you want the REQUEST_BODY and REQUEST_BODY_LENGTH variables to be set?

Because this would allow to be able to have rules matching on the body as a whole.

**Comment by jcchavezs** [comment]
@blotus sorry for the very delayed response. Are you up to contribute such body processor in a PR?

**Comment by jptosso** [comment]
Closing as this is already implemented. Thanks @blotus
