### ISSUE TITLE
Monthly meeting agenda (December 2023) 🎅

### ISSUE THREAD

**Issue by jptosso** [corazawaf/coraza#948]
> This December's meeting will be held the first week of January!

- **Date:** [_Wednesday, January 03 at 12 p.m. UTC_](https://dateful.com/convert/utc?t=12pm&d=2024-01-03)
- **Previous agenda:** https://github.com/corazawaf/coraza/issues/890

### Current agenda
1. https://github.com/corazawaf/coraza/issues/945
2. Feature requests and enhancements
  - https://github.com/corazawaf/coraza/issues/938
  - https://github.com/corazawaf/coraza/issues/929
  - https://github.com/corazawaf/coraza/issues/816
  - https://github.com/corazawaf/coraza/issues/949
  - https://github.com/corazawaf/coraza/issues/728
  - https://github.com/corazawaf/coraza/issues/922 - added by @M4tteoP (with multipart we are storing files and we do not perform any action with them)
  - JSON body-parser, proposal to add a validation check - added by @M4tteoP

### How to join?
1. Join OWASP slack: https://owasp.org/slack/invite
4. Join the #coraza channel: https://owasp.slack.com/archives/C02BXH135AT

### Calendar Event
[Download calendar event (ICS)](https://calendar.google.com/calendar/ical/c_s1vf6auene1ehionfslv010tk8%40group.calendar.google.com/public/basic.ics)

**Comment by jcchavezs** [comment]
Let's please move it to next week as people is off due to
Christmas holidays.

**Comment by fzipi** [comment]
Let's close this one.
