### ISSUE TITLE
Adds support for SecRuleRemoveTargetByTag

### ISSUE THREAD

**Issue by jcchavezs** [corazawaf/coraza#973]
## Summary

Currently we don't have a way to disable rules by Tag and this is crucial as according to https://coreruleset.org/docs/rules/metadata/ there is a good classification of rules in terms of platform, language and attack. This feature would help a lot when it comes to disabled unused rules e.g. when you know we target linux hosts only.

### Basic example

[Include a basic example or links here.
](https://github.com/coreruleset/coreruleset/issues/3523#issuecomment-1919746089)

**Comment by fzipi** [comment]
Sounds good to me.

**Comment by fzipi** [comment]
Hmmm. The directive `SecRuleRemoveTargetByTag` does not exist. It is just used as `ctl:ruleRemoveTargetByTag`, which is already implemented 🤷 

If you intention was about `SecRuleRemoveByTag`... it is already implemented also.

Feel free to close or create additional tickets for better docs.

**Comment by fzipi** [comment]
One thing we might want to take a look is that the [docs for ms 2.x](https://github.com/owasp-modsecurity/ModSecurity/wiki/Reference-Manual-(v2.x)#secruleremovebytag) say that the directive receives a REGEX, and [v3.x says](https://github.com/owasp-modsecurity/ModSecurity/wiki/Reference-Manual-(v2.x)#secruleremovebytag) that the directive receives a TEXT instead.

References:
- https://github.com/owasp-modsecurity/ModSecurity/issues/2540
- https://github.com/owasp-modsecurity/ModSecurity/issues/2109

**Comment by jcchavezs** [comment]
cc @dune73

**Comment by dune73** [comment]
Here is the stuff you need to support.

![tmp](https://github.com/corazawaf/coraza/assets/618722/c4684368-423b-4ce8-8e7f-58fc586ded89)

In ModSec there is also a `...byMsg` variant for all of them (I think), but that's hardly used as far as I can see and I would skip it.

As for the designation of rules, tags and parameters via regex, there support is spotty and not systematically documented in ModSec (apparently my fault as far as the Handbook is concerned). It could be interesting to (a) document that and (b) complement it where useful and to try and bring Coraza in sync.

Pushing forward with Coraza in this area without coordinating with ModSecurity is probably not really a competitive advantage.

**Comment by jcchavezs** [comment]
Thanks for the information @dune73. Given our vision and capacity, our aim here is mainly support CRS4 and users' use cases. Here we are responding to user demand for disabling a tag and luckily we supported it already (along with others that you mentioned in the message above) but I strongly believe we will be implementing directives as long as users request for them or CRS4 requires them.

**Comment by dune73** [comment]
You are free to implement whatever you want. And you do not need my advice.

What I mean to say is: CRS is not using the `byMsg` rule exclusion variant and I doubt it would make sense for you to implement it even if it's technically missing. CRS does not need it and I do not really see widespread use - even if users should demand it from you (which I doubt).

I could think of users asking for advanced rule exclusion constructs such as listing the rule id or tag in a variable, but implementing such a feature in an uncoordinated way would lead to a situation where CRS could probably not make use of it and ModSecurity could have different priorities or ideas how to implement that. The result would be incompatibility on the language level and everybody suffers.

Other features that are not affecting the rule language (eg. transformation caching and other performance improvements) bring a direct competitive edge without the aforementioned challenges.
