### ISSUE TITLE
content-encoding

### ISSUE THREAD

**Issue by Eyup-Devop** [corazawaf/coraza#976]
## Description

Is there a way to process gzip, zlib, br content-encoded response-body?
I realized coraza process response body in raw format.

do I need to create new body processor?

thanks

**Comment by jptosso** [comment]
Hey! Can you provide more details? Is it a programmatic integration or a connector like caddy o wasm ?

**Comment by Eyup-Devop** [comment]
I use coraza as http wrapper in my program which is using reverse proxy. I realized when response is enconded gzip, zlib or br coraza not decompressing before eval. Because I found some blocked request because of php leakage but I didnt find any of it in html code. I found in compressed response.

**Comment by jptosso** [comment]
Unfortunately decompressing is out of the scope of Coraza, I would suggest applying bzip when you find the header and the body is binary 

But I don't see it fitting into the wrapper without breaking integrations

**Comment by Eyup-Devop** [comment]
let me ask you?
is it possible to do that using custom bodyprocessesor?

**Comment by jptosso** [comment]
I wouldn't go that way, I would pre-decompress it and send it to coraza like this:
Just uncompress and copy the buffer.
```go
            gz, err := gzip.NewReader(r.Body)
            if err != nil {
                http.Error(w, "Invalid gzip body", http.StatusBadRequest)
                return
            }
            defer gz.Close()
            io.Copy(tx.RequestBodyWriter, gz)
```

**Comment by jcchavezs** [comment]
Do you mind explaining why @jptosso ?

**Comment by jptosso** [comment]
what if the body has the gzip headers but it is already decompressed? 
I don't think we should even try to touch this layer of the webserver, that's the webserver's problem. It's like telling coraza to do TLS

**Comment by jcchavezs** [comment]
Shall we close this?
