### ISSUE TITLE
AuditLog

### ISSUE THREAD

**Issue by Eyup-Devop** [corazawaf/coraza#977]
## Description

When using custom rule with chain, in audit log there is no chain rule. there is only main rule no chain rule. 

"raw": "SecRule GEO:COUNTRY_CODE \"@within GB,GR\" \"id:1001,phase:1,msg:'country code',deny,status:403, logdata:'Matched Data: %{MATCHED_VAR_NAME}: %{MATCHED_VAR}',chain\"

"orijinal rule": "SecRule GEO:COUNTRY_CODE \"@within GB,GR\" \"id:1001,phase:1,msg:'country code',deny,status:403, logdata:'Matched Data: %{MATCHED_VAR_NAME}: %{MATCHED_VAR}',chain\"
"SecRule REQUEST_URI "@contains /wp-login.php" 

is it normal or it has to full rule.

thanks

**Comment by M4tteoP** [comment]
Hey, it looks like it has been fixed via https://github.com/corazawaf/coraza/pull/985, can we close this?

**Comment by M4tteoP** [comment]
Thanks for this @Eyup-Devop!
